### ISSUE TITLE
List Comprehension

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#112]
As an alternative to #71, list comprehension introduces lists as a critical top-level concept in the pipeline, with similar importance to sections.

Lists can be used in scenarios like
- navigation
- feature lists
- listicles
- product messaging

As a first step, list comprehension will simply look at nested content of list items and make the information available in HTML `class` attributes.

**Comment by kptdobe** [comment]
At the moment, "information available" is NOT available as HTML `class` attributes but as section "types". And I think it should stay like this for now, up to the developer to dump the types as css classes or not. We start having a lot of types computed, we might not want to have all of them.
This may be part of the research here to determine a good format to expose this information for lists.

**Comment by trieloff** [comment]
I think the likelihood of a developer iterating over sections is quite high, but for lists, I'd assume that most are simply passed through.

**Comment by kptdobe** [comment]
I started to look into this.

**Comment by kptdobe** [comment]
The various commits add the "types" info on the section's children (recursive for lists). It does not add the types as css class names but as data.types property on the section mdast nodes. This could be easily be transformed into css class names with the following code:

```js
visit(section, (child) => {
      if (child && child.data && child.data.types) {
        // assign the child types to the child className so that they get rendered
        child.data = Object.assign({
          hProperties: {
            className: child.data.types
          }
        }, child.data || {});
      }
    });
```

**Comment by kptdobe** [comment]
I created https://github.com/adobe/helix-pipeline/issues/198 to follow up on this: document / investigate on the real usage of what is being done here.

**Comment by trieloff** [comment]
I think it wouldn't hurt to directly inject it into the `data.className`, too.

**Comment by kptdobe** [comment]
I do not like that. It adds a lot of css classes you might not want, looks like pollution. Let's go deeper and try to implement some use cases and see what is really useful and how to make use of this. See #198.
