### ISSUE TITLE
Rename to helix-pipeline?

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#113]
Given that all Helix-related repos follow the `helix-*` naming pattern, it might be time to rename this to `helix-pipeline`.

I'm a bit sad to see the name "Hypermedia" go, but it's still in the helix acronym:

**H**ypermedia **E**xperience **L**anguage **I**ntelligizer & e**X**pressifier

**Comment by tripodsan** [comment]
+1

**Comment by rofe** [comment]
+1 i was thinking the same thing

**Comment by stefan-guggisberg** [comment]
+1

**Comment by trieloff** [comment]
@kptdobe can you take a look at the failing smoke test: https://circleci.com/gh/adobe/helix-pipeline/650 the error message looks very un-pipelineish to me.

**Comment by trieloff** [comment]
@sjvs we have renamed another repository `https://github.com/adobe/hypermedia-pipeline/` to `https://github.com/adobe/helix-pipeline/` and would like to update LGTM, too.

**Comment by tripodsan** [comment]
released on npm:

https://github.com/adobe/helix-pipeline/releases/tag/v0.9.0
https://www.npmjs.com/package/@adobe/helix-pipeline/v/0.9.0

**Comment by sjvs** [comment]
@trieloff: LGTM should now automatically pick up on GitHub repository renames. Let me know if that's not the case!
