### ISSUE TITLE
disable GFM autolinking?

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#1203]
it seems that in the current version of the authoring/pipeline that the GFM autolinks are no longer working, because the word2md is escaping the urls:

- https://main--helix-test--tripodsan.hlx3.page/word2md-unit-tests/links.md
- https://main--helix-test--tripodsan.hlx3.page/word2md-unit-tests/links

with the upcoming version of the pipeline, those are rendered again:

- https://main--helix-test--tripodsan.hlx3.page/word2md-unit-tests/links?hlx-pipeline-version=3.11.4-test

although this new behaviour is consistent with github, there is no way for an author to disable the autolinking.

**Comment by rofe** [comment]
I'd say yes: authors can intuitively control in Word/GDocs whether a URL will be rendered as a link. Changing that behavior to always linking URLs no matter what may be annoying.

**Comment by davidnuescheler** [comment]
if i read this correctly, we actually had a conversation about it. 
https://github.com/adobe/business-website/pull/166
i have so say i am a little bit on the fence on it as you may be able to read from my comment.

**Comment by tripodsan** [comment]
I talked with @davidnuescheler and we decided that:

- links in word/google should be links (obviously)
- url/email in word/google should not be links (for now)
- url/email in markdown should be links

this is the behaviour it is right now, so some [changes](https://github.com/adobe/helix-pipeline/commit/6e6c785deb05c9b259bf01db02e4baa6854d6bc0) made in helix-pipeline need to be reverted.

**Comment by tripodsan** [comment]
related issue raised with remark-gfm: https://github.com/remarkjs/remark-gfm/issues/33
