### ISSUE TITLE
Pipeline Sample Fetcher

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#139]
In order to generate more realistic test cases, I propose we create a pipeline sample collection service that accepts JSON documents and stores them. The more samples have already been collected, the fewer new samples should be stored and the more old samples should be dropped, so that there is a quick initial ramp up of samples and then a slow growth once the target, e.g. 1000 samples per project has been reached)

In the pipeline, this will result in one additional step that will take every nth pass and post the current pipeline state to the service.

Adding the step at the beginning of the pipeline will enable the creation of realistic integration tests, as it will be a sample of real production requests coming into the pipeline.

Adding the step right before `once` will enable unit testing of `pre.js`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
