### ISSUE TITLE
Expose sections as documents (VDOM)

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#143]
During the hackathon, I "played" with sections and the first thing I always do is transforming the sections into documents (VDOM) where the API is must front-end developer oriented than MDAST...  See https://github.com/kptdobe/helix-sections-playground/blob/master/src/html.pre.js#L37-L38.

Manipulation, inserting nodes... everything is more simple and in the pre.js, I think a developer would rather care about the DOM than the data structure when consuming sections.

I propose that the pipeline takes care of the transformation.

@trieloff WDYT ?

**Comment by kptdobe** [comment]
Well... +/- the types! 
Maybe the sections should be an object like:
{
  "index": "index of the section in the list",
  "types": ["list of computed types"],
  "document": {VDOM document object}
}

**Comment by trieloff** [comment]
I think just adding a `document` node to each section would do no harm and still grant full access to the MDAST.

**Comment by kptdobe** [comment]
With #279, `<sections>` tags will be added to the `content.document` object (and `<hr>` removed). This will give a VDOM API access on the sections. 2 options now:
1. we do not need this enhancement
2. the idea of a `document` property on each section could be recycled into a reference to the section node inside the `content.document`

**Comment by trieloff** [comment]
> we do not need this enhancement

And in addition, I think we will at some point deprecate `content.sections`.

**Comment by kptdobe** [comment]
Then we need to think where do we put the `mast`, `index` and `types` properties. Maybe as `data` in the VDOM object ?

**Comment by trieloff** [comment]
Good point & good idea.

**Comment by ramboz** [comment]
This has now been tackled in #379 and is in v4.0.0
@kptdobe, @trieloff Would it be safe to close the issue? or do you still see remaining points that aren't covered
