### ISSUE TITLE
Inject Prefetch Links/Headers

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#153]
Goal: improve performance by instructing the browser to prefetch resources likely used to render the page.

How: for the given page, retrieve a list of local resources that have the current URL among its referrers.  Then add the referred URLs to the prefetch headers: https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ

**Comment by trieloff** [comment]
Fastly will automatically push the content for us: 
https://docs.fastly.com/guides/performance-tuning/http2-server-push

**Comment by tripodsan** [comment]
won't fix.
