### ISSUE TITLE
HTML in markdown not supported

### ISSUE THREAD

**Issue by stevengill** [adobe/helix-pipeline#154]
**Description**
If I add an inline html snippet in my mardown file, it doesn't get rendered. 

**To Reproduce**
1. Create hello world
2. add the following snippet at the bottom of `index.md`:

```
<div>test</div>
```
3. Run `hlx up`

**Expected behavior**
I expect `test` to show up on the webpage.

**Version:**
0.10.16

**Additional context**
Traditionally, markdown supports html inline. GitHub seems to support it too. See my markdown snippet being rendered at https://github.com/stevengill/testRepo/blob/master/README.md

**Comment by trieloff** [comment]
This is by design to discourage authors from writing plain HTML and to prevent potentially dangerous HTML.

We can discuss if that's good design or not, and if we should introduce an option to enable HTML-parsing.

**Comment by stevengill** [comment]
I think this is important functionality to have. GitHub, Jekyll, GatsbyJS all support it. 

I was trying to add a `<input>` tag to my markdown. Markdown doesn't have native support for input, so I need to include the html snippet.

**Comment by davidnuescheler** [comment]
I think should definitely support HTML in markdown & pipeline, at this point I find inline HTML the most intuitive way to do forms, and that in itself is a good enough reason to support it for now.
Policing and suppressing the HTML should definitely still be possible via pipeline configuration and/or modification.
