### ISSUE TITLE
md parser regression: setext headings no longer work

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#155]
markdown with headings written with underlines no longer work.

eg:

```
Main Title
=======

Sub Title
---------


````

render perfect in github:

Main Title
=======

Sub Title
---------

but are not detected anymore by the parser. eg:

```html
<title>Main Title
=======================</title>

<p>Sub Title</p>
```

**Comment by rofe** [comment]
Seems like those are recognize as `paragraph` now (and the single underline as `thematicbreak`):
```
{
      "children": [
        {
          "type": "text",
          "value": "Main Title\n========="
        }
      ],
      "type": "paragraph"
    },
    {
      "children": [
        {
          "type": "text",
          "value": "Sub Title"
        }
      ],
      "type": "paragraph"
    },
    {
      "type": "thematicBreak"
    }
```

**Comment by rofe** [comment]
Did this ever work? We updated `remark-parse` from 5.0.0 to 6.0.0 on Oct 23, and it seems that even v5 didn't parse these correctly...

**Comment by tripodsan** [comment]
> Did this ever work?

yes. the initial examples in the demo was with `======`.

**Comment by rofe** [comment]
Looks like setext headings were disabled deliberately in d45ab11a5a2f4191369cf4c8c2e21fde52e25fd7 to fix some grayscale issue: 
https://github.com/adobe/helix-pipeline/blame/master/src/html/parse-markdown.js#L43

@trieloff

**Comment by trieloff** [comment]
I think the best solution would be to
1) fix the upstream https://github.com/remarkjs/remark-frontmatter so that it does not confuse setext headings with yaml fences
2) remove the lines that disable setext headings here

**Comment by rofe** [comment]
For 1, it would be great if you could create the issue in remarkjs because you can best describe the original use case you worked around.
I can take care of 2.
