### ISSUE TITLE
Single element in markdown not being rendered

### ISSUE THREAD

**Issue by koraa** [adobe/helix-pipeline#157]
Single element inside markdown is not being printed.

```
# Foo
```

```
Foo
```

This seems to be caused by the markdown parser not generating a surrounding `<div>` for single element
markdown, which the `emit` pipeline step expects: `document.body.firstChild.childNodes`.
We could either 1) make sure we generate the `<div>` for single element markdowns 2) never generate the div (as most markdown generators do)
and add it later 3) handle that case in `emit` specifically.

**Comment by koraa** [comment]
Possibly related: #156

**Comment by trieloff** [comment]
I'd make `emit` more robust, so that we can deal with possible Markdown changes that are user-created.
