### ISSUE TITLE
Bring back process

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#167]
> arff... no... too fast...
> I use the `process` method because it returns a node only and not a full document! See > https://github.com/kptdobe/helix-sections-playground/blob/master/src/html.pre.js#L50

_Originally posted by @kptdobe in https://github.com/adobe/helix-pipeline/pull/163#issuecomment-457817570_

**Comment by kptdobe** [comment]
Thanks @trieloff 

We could just expose a `getNode` method instead of `process`. You would then only have `getDocument` or `getNode`.
