### ISSUE TITLE
Clarify request url, path and introduce root

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#170]
When a strain is selected with a URL condition, it is expected that the content repository is mounted below the url path. for example:

```yaml
strain:
  url: https://www.project-helix.io/docs/api
  content: https://github.com/adobe/helix-docs.git#master/documentation.
```

should map a request of `https://www.project-helix.io/docs/api/general/index.html?a=1` to
`https://github.com/adobe/helix-docs.git#master/documentation/general/index.md`.

the `context.request` object should have:

| property | value | comment |
|----------|------|-----------|
| `url` | `/docs/api/general/index.html?a=1` | the original client request url |
| `path` | `/general/index.md` | the _resource_ path |
| `root` | `/docs/api` | **new**: The mount root |

### Suggest

It might be confusing to have `request.path` different from `request.url`. so I suggest to introduce `resourcePath`, and keep the `path` the original client `path`.

| property | value | comment |
|----------|------|-----------|
| `url` | `/docs/api/general/index.html?a=1` | the original client request url |
| `path` | `/docs/api/general/index.html` | the original request path |
| `resourcePath`<sup>2</sup> | `/general/index.md` | the _resource_ path |
| `root` | `/docs/api` | The mount root |

<sup>2</sup> Alternative: `contentPath`

/cc @trieloff, @kptdobe @stevengill

**Comment by stevengill** [comment]
Hey @tripodsan 

I'd say this is a good enhancement. Currently, I have no way to get the mount root in my pre.js file for my dispatcher.

**Comment by stevengill** [comment]
Four places I currently need the mount points:

1) the dispatcher
2) Before loading summary.htl, we need to figure out the location of summary.md. Need to add the mount point in there
3) The side nav in the docs (where we convert the links to absolute links
4) Any image tags in the content markdown repo. They link locally to images in the assets directory locally in their own repos. These links need to be rewritten with mount points.

**Comment by trieloff** [comment]
+1

**Comment by tripodsan** [comment]
New suggestion: add `resourcePath` and `rootPath` to `action.request`, use url based path in `context.request`:

| property | value | comment |
|----------|------|-----------|
| `context.request.url` | `/docs/api/general/index.html?a=1` | the original client request url |
| `context.request.path` | `/docs/api/general/index.html` | the original request path |
| `action.request.resourcePath` | `/general/index.md` | the _resource_ path |
| `action.request.rootPath` | `/docs/api` | The mount root |
