### ISSUE TITLE
Markdown rendering can't handle references to links

### ISSUE THREAD

**Issue by stevengill** [adobe/helix-pipeline#178]
See https://github.com/adobe/developer.adobe.com-planning/issues/106

Essentially the following markdown would throw an error:

```
This is a [LINK][link1]

[link1]: https://mylink.com
```

**Comment by trieloff** [comment]
I think this was fixed in #213, please re-open if it persists.

**Comment by filmaj** [comment]
Confirmed this is now fixed, thanks.
