### ISSUE TITLE
Section Improvements

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#185]
See also #175 – @koraa I've written down my design notes for how I think sections, type inference, HTML transformation, etc. should work. Comments welcome:

# HTML Pipeline Extensibility

This is a proposal to enable extensibility of the HTML Pipeline in Project Helix with increased ease of use and less potential for error.

## Pipeline Architecture

The purpose of the HTML pipeline is to fetch, parse, and transform markdown into customer-defined HTML. The pipeline includes two key extension points:

1. the template (also `*.htl`) is a customer-defined function that is typically written using a declarative templating language. Although HTL is the most common templating language, the Helix Pipeline architecture is agnostic to the specific template language as long as it can be compiled into a single pure function. In general, the template can be expected to be purely read-only, declarative and without side-effects.
2. the preprocessing function (also `*.pre.js` or Pre-JS) is a customer-defined function written using imperative JavaScript that is being used to manipulate the Payload data structure so that it can be consumed conveniently in the template. Ideally, the Pre-JS encapsulates all imperative business functionality, so that the template can be purely for styling purposes.

While template and Pre-JS work in tandem, for the purpose of creating maintainable and re-usable code, it is desired to keep the amount of Pre-JS functionality as small as possible. When there is functionality that frequently gets implemented in various preprocessing functions, it is advisable to pull that particular functionality into the Helix Framework.

## Pipeline Data Structures

Helix is operating on a number of key data structures. Earlier data structures are consumed by pipeline functionality and extension scripts to create latter data structures. The key structures in order are:

1. the `request` represents the resource (URL) that the visitor requested. Based on the `request`, the `content` is retrieved and transformed.
2. The `mdast` is the canonical representation of the Markdown document, i.e. the content as created by the author, in a format that can be understood easily. The `mdast` (Markdown Abstract Syntax Tree) should be the representation of the content that is most in line with the author's intent and should express the meaning of the document in the most reliable way.
3. The `document` or DOM (Document Object Model) represents the content after it has been transformed into HTML. In order to enable further manipulations of this data structure, the JavaScript DOM API is emulated, so that client-side web developers can use a familiar API to operate on the generated HTML.
4. The `response` is the byte stream that will finally be served back to the client, after all template transformations have been applied and the document has been serialized as a HTML document.

In an ideal scenario, the flow of `request->mdast->document->response` is intercepted and adjusted by the developer in two places:

```
  request ----> mdast ----> document ----> response
          \_________pre.js________/\_htl_/
```

Ideally, the contents of the `pre.js` would represent the uni-directional flow of data as best as possible.

## Sections and Metadata

Helix is using the notion of sections to create further substructures in a document. A section:

- is part of a Markdown document
- cannot contain other sections
- can carry metadata such as: title, introduction, type/class, strain condition (section will be only shown for the listed strains), test group (section will be only shown if it is selected in an A/B test)

As part of the markdown parsing steps in the pipeline, sections will be detected and types/classes will be inferred based on the content of the section.

## Common Use Cases and Desired Usage Patterns

In the following sections, a number of common usage scenarios for the pipeline customizability will be illustrated:

1. Wrapping Output
2. Wrapping Sections
3. Emitting Metadata
4. Adding Metadata
5. Emitting Types
6. Inferring Types
7. Modifying MDAST
8. Customizing Transformation
9. Overriding Output

### Wrapping Output

> I want to create HTML output that contains custom headers and footers.

Solution: simply add the wrapper to the template and use `document.body.innerHTML` to get the HTML contents.

`html.htl`

```html
<html>
    <head>
        <title>My Site</title>
    </head>
    <body>
        <nav>Navigation Here</nav>
        <main>
            ${content.document.body.innerHTML}
        </main>
    </body>
</html>
```

### Wrapping Sections

> I want the same, but each section should be wrapped with a custom preamble.

Solution: iterate over the sections, and use each section's `dom` representation to get the HTML content of the section.

`html.htl`

```html
<html>
    <head>
        <title>My Site</title>
    </head>
    <body>
        <nav>Navigation Here</nav>
        <main data-sly-list="${content.mdast.sections}">
            <section class="mysection">
                <h1 class="intro">${item.meta.title}</h1>
                ${item.dom.innerHTML}
            </section>
        </main>
    </body>
</html>
```

### Emitting Metadata

> I want the introduction paragraph in the description meta tag, because I believe it improves SEO. I also want the correct page title.

Solution: use the `content.meta` data.

`html.htl`

```html
<html>
    <head>
        <title>${content.meta.title}</title>
        <meta 
            name="description"
            content="${content.meta.intro}">
    </head>
    <body>
        <nav>Navigation Here</nav>
        <main data-sly-list="${content.mdast.sections}">
            <section class="mysection">
                <h1 class="intro">${item.meta.title}</h1>
                ${item.dom.innerHTML}
            </section>
        </main>
    </body>
</html>
```

### Adding Metadata

> I want a custom App Store link in the page metadata

Solution: use `pre.js` to inject a metadata property into `content.meta`.

`pre.js`

```javascript
function pre(payload) {
    payload.content.meta.appstore = {
      id: 'foo',
      affiliate: 'bar'
    }
}
```

`html.htl`

```html
<html>
    <head>
        <title>${content.meta.title}</title>
        <meta 
            name="description"
            content="${content.meta.intro}">
        <meta 
            name="apple-itunes-app" 
            content="app-id=${content.meta.appstore.id}, 
            affiliate-data=${content.meta.appstore.affiliate}">
    </head>
    <body>
        <nav>Navigation Here</nav>
        <main data-sly-list="${content.mdast.sections}">
            <section class="mysection">
                <h1 class="intro">${item.meta.title}</h1>
                ${item.dom.innerHTML}
            </section>
        </main>
    </body>
</html>
```

### Emitting Types

> Want the correct CSS classes for each section in the HTML output. Our design system mandates that each class name starts with `cls-`.

Solution: use `content.mdast.sections[].type` and add it to the HTML.

`html.htl`

```javascript
function pre(payload) {
    payload.sections.forEach(section => {
        section.mytype = section.type.map(name => `cls-${name}`).join(' ');
    });
}
```

`section.type` is set as an array of inferred types.

```html
<html>
    <head>
        <title>${content.meta.title}</title>
        <meta 
            name="description"
            content="${content.meta.intro}">
        <meta 
            name="apple-itunes-app" 
            content="app-id=${content.meta.appstore.id}, 
            affiliate-data=${content.meta.appstore.affiliate}">
    </head>
    <body>
        <nav>Navigation Here</nav>
        <main data-sly-list="${content.mdast.sections}">
            <section class="mysection ${item.meta.mytype}">
                <h1 class="intro">${item.meta.title}</h1>
                ${item.dom.innerHTML}
            </section>
        </main>
    </body>
</html>
```

### Inferring Types

> I want that sections that contain three headings and nothing else get the `cls-super-heading` class.

Solution: customize the type inference engine:

```javascript
function pre(payload, context) {
    payload.typematcher.match('^heading heading heading$', 'super-heading');
    payload.sections.forEach(section => {
        section.mytype = section.type.map(name => `cls-${name}`).join(' ');
    });
}
```

Calling `payload.typematcher.match()` will reconfigure the [type-matcher](https://github.com/adobe/helix-pipeline/blob/master/src/utils/match-section-types.js), so that the next time types are accessed, the new mapping takes effect. Ideally, we should be able to do this without an additional explicit call to recalculate the section types.

### Modifying MDAST

> I want that all headings start with the text `TOP`.

Solution: use `unist-util-map` to go over all headings and add a new text node.

```javascript
const map = require('unist-util-map')

function isheading(node) {
    return node.type == 'heading';
}

function addtext(node) {
    if (isheading(node) {
        node.children.unshift({ type: 'text', value: 'TOP '});
    }
    return node;
}

function pre(payload, context) {
    payload.typematcher.match('^heading heading heading$', 'super-heading');
    payload.sections.forEach(section => {
        map(section, addtext);
        section.mytype = section.type.map(name => `cls-${name}`).join(' ');
    });
}
```

Again, ideally, modifications of any `content.sections` element would either re-trigger the HTML transformation, or the transformation itself would be lazy, waiting for the property to be accessed.

### Customizing Transformation

Note: There is already an [MAST-to-VDOM transformation utility](https://github.com/adobe/helix-pipeline/blob/master/src/utils/mdast-to-vdom.js).

> I want to remove the HTML output of all images that have an empty alt tag.

Solution: customize the transformation engine:

```javascript
function pre(payload, context) {
    payload.htmltransformer.match("image[@alt='']", '<div class="omitted">image omitted</div>');
}
```

As before, let's make the `htmltransformer` lazy, so that no extra call is necessary.

### Overriding Output

> Remove all links from the output.

Solution: directly access the DOM.

```javascript
function pre(payload, context) {
    Array.from(payload.document.getElementsByTagName('a')).forEach(a => {
        a.parentNode.removeChild(a);
    });
}
```

Ideally, this would also affect `document.sections[].dom`

**Comment by tripodsan** [comment]
- in the _Modifying MDAST_ `pre.js`, I don't see how the `addText()` is used.

**Comment by trieloff** [comment]
@tripodsan good eye: I've changed

```javascript
map(section)
```

to

```javascript
map(section, addtext)
```

**Comment by koraa** [comment]
Looks great!! Since you have a very good understanding of how sections should work, I suggest you go ahead and take over the implementation of section improvements!

**Comment by kptdobe** [comment]
This is a great start and is already (almost) doable today. 
(for the record and for further brainstorming) You might quickly hit some more complex use cases like:

For my section A, default output from pipeline is:

```
<section>
  <h2>section.title</h2>
  <img src="section.img.src"/>
  <p>section.text</p>
</section>
```

but I need it to be:

```
<section class="section_A">
  <div class="title">
   <h2>section.title</h2>
  </div>
  <div class="content">
    <div class="img">
      <img src="section.img.src"/>
    </div>
    <div class="text">
      <span>section.text</span>
    <div>
  </div>
</section>
```

**Comment by trieloff** [comment]
Maybe it would make sense to introduce a `wrap` function to `VDOMTransformer` that works almost like `match`, but simply wraps the element that the normal transformation would produce.
