### ISSUE TITLE
Frontmatter not digested by the sections

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#205]
While exploring how to make the best use of sections (see #198), I found frontmatter blocks specified in the document are not properly digested by the section split.

Example:

```md
---
layout: header
---

# Page title

## Section 1 title

Some text

---

---
layout: main
---

## Section 2 title

More text

```

I expect the sections array to contain 2 arrays:

1. section 1: `{ title: 'Section 1 title', meta: { layout: 'header'}, children: [...]}`
2. section 1: `{ title: 'Section 2 title', meta: { layout: 'main'}, children: [...]}`

The current sections array contains multiple "issues":

1. the first section title is `Page title` (should be `Section 1 title`)
2. the first section contains a YAML node with the meta (should not be there)
3. the second section is empty
4. a third section which contains what I expect to be the second one with title `layout: main`
5. no meta in the third section

The section split is somehow not working as expected.

**Comment by trieloff** [comment]
I'd say it's working as designed. Take out the `---` between the sections and you get two sections.

The section title is always the title of the first heading.

**Comment by kptdobe** [comment]
Humm.. interesting. I tried that last time, it did not work. Not sure why. I get 2 sections now as expected!

> The section title is always the title of the first heading

Since we consider the first title as the page title, maybe we should add some smartness here for the first section.
