### ISSUE TITLE
json pipeline is not usable

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#218]
1. Create a `json.htl` with content:

```
${content}
```

2. Create a `json.pre.js` with content: 

```
function pre(payload, action) {
  payload.content = JSON.stringify(payload.content);
}

module.exports.pre = pre;
```

3. Run `hlx up` and request http://localhost:3000/index.json

According to the code, this should work but it only outputs:

```
[object Object]
```

Expected: the payload content should be rendered.

A first debugging session revealed that this line is the issue: https://github.com/adobe/helix-simulator/blob/master/src/HelixServer.js#L191
Removing that line fixes the issue.

Removing the `stringify` in the `pre.js` does not solve the pb (should not be necessary from my pov).

More analysis required.

**Comment by trieloff** [comment]
Writing to `content.something` would be more consistent than writing to `response.body`, even if it is a minor indirection.

**Comment by rofe** [comment]
Yes, but then we'd also need an `emit` (and `validate`?) step...
