### ISSUE TITLE
Document the use of the JSON pipeline

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#220]
https://github.com/adobe/hypermedia-pipeline/issues/16 has been merged with no explanation / sample on how to use it. ootb, it cannot work since Petridish has not been modified, I do not see how this could be used but maybe I missed something...

cc @trieloff

**Comment by kptdobe** [comment]
Use of JSON pipeline now documented here: https://github.com/adobe/helix-cli/blob/master/docs/usage.md

**Comment by rofe** [comment]
Why `helix-cli` and not `helix-pipeline`? I would sort of expect to find `usage.md` there...

**Comment by filmaj** [comment]
@rofe maybe both? The details of module usage inside pipeline, but a higher-level approach / introduction in cli?

**Comment by rofe** [comment]
On second thought, I think eventually all of this should be in `project-helix.io`

**Comment by kptdobe** [comment]
helix-pipeline is too low level, you cannot do really use all of this without `hlx up`.
And this is how you use Helix, helix-cli is the entry point.
`project-helix.io` should definitely present the same content in a start and nice way. This is a bit "raw".

**Comment by kptdobe** [comment]
Btw, maybe we should first tackle https://github.com/adobe/project-helix/projects/6 (check the project goals) :)
