### ISSUE TITLE
Write protection in the pipeline not fully functional

### ISSUE THREAD

**Issue by koraa** [adobe/helix-pipeline#228]
The Pipeline class implements write protection, so pipeline steps cannot modify their arguments.

In order to do this, the lodash.merge function is applied to the current data before each pipeline step. This way pipeline steps/.every() steps can modify the current data, but it won't have an actual effect since they are modifying a copy.

This approach has some drawbacks:

1. The amount of work to be done grows roughtly `(pipeline_steps * datasize)`, which can be quite a lot
2. This approach only work on arrays and plain objects; other types (like the DOM) can still be modified
3. The approach has the potential to hide a lot of bugs; e.g. accidental modification which is hidden, or third party steps could be modifying the data intentionally and not notice their notifications are discarded (e.g. due to improper testing)

I can see some ways to remedy this:

1. Allow data modification
2. In order to remedy point `(2)` we could introduce a deepClone function of our own based on traits; this function would throw for unknown types instead of just not clone them. Devs could react to those exceptions by simply adding an implementation for the type
3. We could use an immutable js lib to actually write protect the data (and throw if modification is attempted). This would necessitate a freeze/thaw API, probably trait based so it can be extended with custom types when the need arises.

Even though I would enjoy adding some more traits, I think the best way to go is to use (1); we are (unfortunately) in a language that does not natively support `const` attributes, so emulating them somehow is admittetly very hard. Solution 2 and 3 would both put a lot of extra work on third party devs if they want to use pipelines with their custom types.

Allowing modification is the usual thing to do in js…

**Comment by trieloff** [comment]
We should probably handle this together with #223

**Comment by tripodsan** [comment]
+1 for (1). having _middleware_ operating on the req/res is quite common in the js world.

**Comment by kptdobe** [comment]
+1 for (1). without building a complex and costly machinery, this is almost impossible to do.

**Comment by rofe** [comment]
+1 for (1) for the reasons already stated
