### ISSUE TITLE
context.request.path & context.request.url are incorrect for subdirectory strains

### ISSUE THREAD

**Issue by stevengill** [adobe/helix-pipeline#254]
Related to https://github.com/adobe/helix-simulator/issues/186.

I believe the `context.request.path` and `context.request.url` variables need to be updated to handle subdirectories.

Example Strain
```
  - name: contributor-docs-helixdemo
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/contributor/docs
    content: https://github.com/AdobeDocs/contributor.en.git/help#master
    directoryIndex: introduction.html
    package: developer-adobe-com/756ec092f2585c73ef0b75ba1caf8a698091d44a
```
variable values:
* `context.request.path` = `/contributor/docs/help/introduction.html`
* `context.request.url` = `/contributor/docs/help/introduction.html`
* `action.request.params.path` =  `/help/introduction.md`
* `action.request.params.rootPath`  = `/contributor/docs`

I believe the `context.request.path/url` should be `/contributor/docs/introduction.html`. `action.request.params.path` might also be wrong. Not sure if it should include the `/help` part.

**Comment by tripodsan** [comment]
quick fix would be to use the `action.params.headers['x-old-url']` as `request.path`, but probably better to include `contentRoot` and/or `pathInfo` directly in the action params.

@trieloff WDYT?

**Comment by tripodsan** [comment]
if the request to a directory, the `request.path` should also be the original one:

request to `/contributor/docs/` with the strain above above, should yield:

| property | value |
|----------|-------------|
| `context.request.path` | `/contributor/docs/` |
| `context.request.rootPath`<sup>1</sup> | `/contributor/docs` |
| `context.request.pathInfo` | `` |
| `action.request.params.path` | `/help/introduction.md` |
| `action.request.params.contentRoot` | `/help` |
