### ISSUE TITLE
Discussion: Introduce GitHub Content Proxy?

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#264]
> I would not mix the caching issue which leads to use `api` instead of `raw` and the authorized requests: these are 2 different issues which must be treated separately. Mainly to avoid a big PR with a lot of regressions...

right: there are 2 points here:

1. use API or RAW to fetch the markdown (and statics, btw)
2. authenticate the request or not.

(2) is required for private repository access. this is irrespective which endpoints to use.
(1) leads to better cache freshness on github's side. but comes with the drawback, that unauthenticated requests have a limit of 60/s. 

What makes @koraa's problem worse is, that the simple-setup renders everyones content with the same user, even if authenticated. 

What about having a hybrid solution, with fastly acting as "content-cache"? :
- request content through fastly: `https://content.project-helix.io/tripodsan/hlxtest/index.md`
- use github API as backend, authenticated if possible. calculate a surrogate key based `owner/repo`.
- when invalidate the cache, use the `owner/repo` key

this give the advantage:
- that we control the content cache completely
- we can set max-age to infinity, since we always know what to purge
- very few requests to API

---
_Originally posted by @tripodsan in https://github.com/adobe/helix-pipeline/pull/262#issuecomment-483519336_

**Comment by trieloff** [comment]
I'm not sure if we can use only Fastly, without going back to Adobe I/O Runtime, because `http https://api.github.com/repos/adobe/helix-cli/contents/README.md Accept:vnd.github.VERSION.raw` will return a JSON for me, not the raw Markdown. This means we have to do JSON and Base64 decoding (which Fastly can't do), which complicates the entire setup.

If I understand your suggestion correctly, we would blast the entire cache for `user/repo`, not just for the files that changed. Why?

How would be manage authentication if we have a central proxy service? We might be able to get keys from the bot, but we need to map keys to repos and we would implicitly make any private repo readable through the key sharing.

**Comment by tripodsan** [comment]
you have the wrong accept header:

```
curl -v -H "Accept: application/vnd.github.VERSION.raw" https://api.github.com/repos/tripodsan/hlxtest/contents/README.md
```

renders the raw response.

**Comment by tripodsan** [comment]
> If I understand your suggestion correctly, we would blast the entire cache for user/repo, not just for the files that changed. Why?

as a fist stab, yes. but of course, we can invalidate all modified files. it shouldn't bee to difficult to gather them from the push events. but then problem usually is, that if you miss an event, you need to calculate the list of the modified files since the last state manually - and this is not possible.

> How would be manage authentication if we have a central proxy service?

for @koraa's project, all repos are public anyways.

for private repositories, we would need to compare the token with the one stored in the edge dictionary....

**Comment by trieloff** [comment]
Maybe we can be smarter about that:

If we request `https://raw.githubusercontent.com/adobe/helix-cli/410b3c5dd2197002a2a30caa512ee0a0f1bce683/README.md`, we get a specific version, fresh, unchangeable and not rate limited.

What we need, is a service that translates the triple `adobe/helix-cli/master` into `410b3c5dd2197002a2a30caa512ee0a0f1bce683 ` and caches that translation as long as the repository does not change.

So what about building this kind of service:

1. `GET https://resolve.project-helix.io/adobe/helix-cli/master/`
2. (if not cached): call the GH API and run the equivalent of `http https://api.github.com/repos/adobe/helix-cli/branches/master | jq .commit.sha`
3. `302  https://raw.githubusercontent.com/adobe/helix-cli/410b3c5dd2197002a2a30caa512ee0a0f1bce683/`
4. the response uses `adobe/helix-cli` as surrogate key
5. the bot flushes the surrogate key cache when an update to the repo is detected

And a second service:

1. `GET https://content.project-helix.io/adobe/helix-cli/master/README.md`
2. GET `https://resolve.project-helix.io/adobe/helix-cli/master/`
3. combine the `Location` header from (2) with the file path from (1) to get `https://raw.githubusercontent.com/adobe/helix-cli/410b3c5dd2197002a2a30caa512ee0a0f1bce683/README.md`
4. add the `adobe/helix-cli/master` Surrogate-Key
5. deliver whatever comes from the URL constructed in (3)

**Comment by koraa** [comment]
so fastly -> adobe-io -> fastly -> gh?

**Comment by koraa** [comment]
> What about having a hybrid solution, with fastly acting as "content-cache"? :
> - request content through fastly: `https://content.project-helix.io/tripodsan/hlxtest/index.md`
> - use github API as backend, authenticated if possible. calculate a surrogate key based `owner/repo`.
> - when invalidate the cache, use the `owner/repo` key

This pretty much is how the simple-deployment works right now :)

**Comment by trieloff** [comment]
> In computer science, every problem can be solved by adding another layer of abstraction. That is, every problem but the problem of having too many layers of abstraction.

Between `api` and `raw` GitHub is making a tradeoff between consistency and cost. `api` is expensive, but consistent (hence rate limited) and `raw` is cheap and fast, but inconsistent. If we want to move the point of tradeoff, we have to build our own service, using the available ingredients.

@koraa for your problem at hand, maybe you should add a fetch step that uses the API if a token is made available. It happens before the regular `raw` fetch step which stays the way it is for now and you can make progress with your bot based deployment, even if you know that you will eventually run into rate limit issues.

**Comment by koraa** [comment]
@trieloff Yeah, that's pretty much what I plan to do; although the bot deployment uses a central wsk action right now, so I will have to introduce mutliple actions first. I think I will work on the bot based deployment as  feature branch for a while :)

**Comment by tripodsan** [comment]
@trieloff both services can be implemented in a VLC, right?

**Comment by trieloff** [comment]
@tripodsan the first one can't:

> 2. (if not cached): call the GH API and run the equivalent of `http https://api.github.com/repos/adobe/helix-cli/branches/master | jq .commit.sha` (we'd need Runtime for that)

But, we might be able to use `isomorphic-git` for this instead of the GH API, so we can circumvent the rate limit.

**Comment by stefan-guggisberg** [comment]
> But, we might be able to use isomorphic-git for this instead of the GH API, so we can circumvent the rate limit.

could you please elaborate?

**Comment by trieloff** [comment]
The https://isomorphic-git.org has a "try it out" section, which gets the branches and tags from a HTTPS Git URL. If we can get the latest sha for each of the branches, we are set.

**Comment by tripodsan** [comment]
> The https://isomorphic-git.org has a "try it out" section, which gets the branches and tags from a HTTPS Git URL. If we can get the latest sha for each of the branches, we are set

but they will also have a rate limit...and it's probably even worse....

> the first one can't:

why not? can't you parse json in fastly ? or regexp it out?
maybe use https://blog.cloudflare.com/cloudflare-workers-unleashed/ ?

**Comment by trieloff** [comment]
You can't read the response body in VCL, everything else would be easy. Speaking with @stefan-guggisberg, the key request is this one: `curl 'https://github.com/adobe/helix-cli.git/info/refs?service=git-upload-pack`.

We can build a minimal action (no dependencies) that we can deploy anywhere, but for simplicity sake, I'd start with Adobe I/O Runtime

**Comment by stefan-guggisberg** [comment]
> We can build a minimal action (no dependencies) that we can deploy anywhere, but for simplicity sake, I'd start with Adobe I/O Runtime

like this? https://github.com/stefan-guggisberg/git-resolve-branch

```bash
wsk action create git-resolve-ref index.js
wsk action invoke git-resolve-ref --param org "adobe" --param repo "helix-cli" --param branch "issue654" --result
```

**Comment by trieloff** [comment]
@stefan-guggisberg exactly like this. Some suggestions:

- [ ] I'd rename the `branch` parameter to `ref`
- [ ] maybe see if we can allow early termination, i.e. return from `on('data')` instead of `on('end')`
- [ ] move to `adobe/helix-resolve-git-branch`

**Comment by stefan-guggisberg** [comment]
@trieloff https://github.com/adobe/git-resolve-ref

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
