### ISSUE TITLE
Introduce context.response.hast?

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#285]
In #281 I'm parsing the HTML string from `context.response.body`, then transform it, then write it back to `context.response.body`. Great.

For #153 I would benefit from having access to the parsed response HTML, because I could then walk over the AST, find all `a` elements, and add their `href`s to the `link` header to enable pre-fetching.

In #122 I would benefit from having access to the parsed response HTML, because I could then walk over the AST, find all `meta` elements, and add some of them to the response headers.

Therefore, I propose the creation of a new `parse-response-html` step, a `context.response.hast` property and a new `stringif-response-html` step for the HTML pipeline.

**Comment by tripodsan** [comment]
please ensure that the parse->stringify preserves whitespace and comments (at least in debug mode). developers don't like it, when their HTML gets scrambled :-)
