### ISSUE TITLE
Previewing markdown

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pipeline#292]
(spin-off from #251)

Add either a dedicated pipe or extend the existing html pipe to take markdown from the POSTed request.body, proxy the html pipe, and wrap the generated output in a JSON object:
```
{
  "content": "<!doctype html>... "
}
 ```
This would be a safe way to support live (read: "as you type") previewing of markdown using Helix (for example using a [browser extension](https://github.com/adobe/helix-markdown-preview)).

The simplest and most transparent solution would be to register a new pipeline to a `.preview.json` selector/extension combo, and have editing tools POST there.

A more sophisticated solution would be to use a vendor specific mime-type like `application/vnd.helix.preview+json` in the `Accept` header, so the POST could be made to the original (`.html`) path, and pipe resolution would be handled by Fastly based on the header.

**Comment by trieloff** [comment]
Taking the POST body seems fine, switching the content type from HTML to JSON is something I'd want to avoid.

**Comment by rofe** [comment]
So you would prefer the simple solution, i.e. posting to `/bla.preview.json`?

**Comment by tripodsan** [comment]
we need to post to the action that is actually doing the transformation. I don't see the `html` action as something that needs to respond with `text/html`. if the requested media type is json, we should give json. 

I think this should be a generic feature of the pipeline, to suppress the `emit` step of the default media type, and respond with an alternative.

**Comment by tripodsan** [comment]
> So you would prefer the simple solution, i.e. posting to `/bla.preview.json`?

I wouldn't do this, otherwise you can never request a preview with a different selector or extension.

**Comment by trieloff** [comment]
If we do this, we need to be careful on the Fastly side. Making the first request with an Accept header can poison the cache, unless we vary on Accept (which reduces cache efficiency). We can handle it in VCL, just need to be aware of it.

**Comment by tripodsan** [comment]
also, this issue is about how the pipeline should handle the request, and not how this is mapped in fastly :-)

**Comment by trieloff** [comment]
@rofe I think you can start with the POST reading-part and we can decide if JSON responses are really needed later.

**Comment by tripodsan** [comment]
I think this is all _wrong_ :-) operations like this, should actually be made against a (yet to be defined) **helix-content API**.

**Comment by tripodsan** [comment]
> I think you can start with the POST reading-part and we can decide if JSON responses are really needed later.

we already have the POST part. if we POST directly to the action. the problem is:
1. how do we access this through fastly?
2. how do we respond with JSON

**Comment by trieloff** [comment]
> 1. how do we access this through fastly?

What's so bad about calling the action directly?

> 2. how do we respond with JSON

What's so bad about responding HTML?

**Comment by rofe** [comment]
> we already have the POST part

correct, see https://github.com/adobe/helix-simulator/issues/179 and https://github.com/adobe/helix-pipeline/issues/235

**Comment by rofe** [comment]
> What's so bad about calling the action directly?

how does the editing tool (or worse, the end user) know the action URL?

> What's so bad about responding HTML?

CORS.

**Comment by trieloff** [comment]
> CORS

We can set the `Access-Control-Allow-Origin` header from within the action. 

> how does the editing tool (or worse, the end user) know the action URL?

Ask Fastly? Maybe through a `.hlx_edit` URL extension that simply redirects to the correct action URL?

**Comment by trieloff** [comment]
The things that I'd look at for editing-optimized HTML output is:
- mapping hints for position in HTML to position in Markdown
- cursor indicators
- select range indicators

**Comment by rofe** [comment]
for completeness: we don't have to set the `Access-Control-Allow-Origin` header in the action, Bladerunner/OpenWhisk does that by default. So posting to the action directly would eliminate the CORS issue.

**Comment by rofe** [comment]
> Ask Fastly?

Not sure if we really want to keep it that easy to find out the backend URL...

**Comment by lkrapf** [comment]
@trieloff:
> What's so bad about responding HTML?

Because by making your browser post to the preview action, an attacker can get it to render HTML (potentially even JS), *served from a trustworthy domain*. If the response is JSON, which gets only rendered by the extension this would not work.

**Comment by trieloff** [comment]
@lkrapf I don't share the assumption that the editor is running on the same domain as the site and I'd also assume that the preview function itself requires authentication.

**Comment by rofe** [comment]
Ah, so CORS is a different issue, independent of the content-type. Sorry for the confusion.

**Comment by lkrapf** [comment]
@trieloff 
> I don't share the assumption that the editor is running on the same domain as the site 

Neither do I. The attack works as follows:
1. The attacker makes you visit attacker.com
2. Your browser will automatically POST some attacker controlled content to trusteddomain.com/preview.json

If the response is HTML you will get it rendered in the browser served from (even signed by) trusteddomain.com, with no indication where the content is originally coming from.

> and I'd also assume that the preview function itself requires authentication.

Then this attack turns into CSRF - which is yet another issue.

I agree with @tripodsan. The best option would be to turn this into an API.

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
