### ISSUE TITLE
Nicer quotes for HTML attributes that contain ESI

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#309]
I'm setting the `href` value to be the string `<esi:include src="foo"/>`. You might try to change it to `<esi:include src='foo' />`. `quoteSmart` would then switch the outer quotes to `"`, so that no escaping of the inner quotes is needed.

_Originally posted by @trieloff in https://github.com/adobe/helix-cli/issues/813#issuecomment-489976645_

**Comment by tripodsan** [comment]
this is no longer relevant, as it is now automatically adjusted with the new jsdom/htlengine #337
