### ISSUE TITLE
responsive image use needs to be more specific and selective

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pipeline#320]
we are currently attaching `srcset` and `sizes` to all images we find in markdown.

however responsive images are only useful when an image is scaling with the viewport size and pixel density. so only an image that has a computed size that is materially impacted by a change in  `vw`, `vh`. simple examples are width images.

there are a number of images, like logos, icons or inline images that do not materially change their width and/or height as they are part of a responsive layout. many of those images also are very small assets to begin with and the potential gain of serving responsive images is very small, and may potentially be offset by a complicated `srcset`.

on top of that it is in html source to see those complicated `srcset` attributes in images that clearly don't need them.

in addition to that, the default behavior of `srcset` & `sizes =100vw` of scaling the calculated image size directly proportionate to the `vw` creates a unexpected effect for inline images and seems to be very hard to combat without explicitly setting the `width` of an image.

my proposal is to remove the responsive image from the default pipeline and instead offer a utility function that allows someone to insert response images selectively in the `pre.js` step.

**Comment by trieloff** [comment]
@davidnuescheler I've managed to reproduce the scaling issue you've seen with inline images here: https://codepen.io/trieloff-the-flexboxer/pen/RmrvvG

**Comment by trieloff** [comment]
Setting an additional `width: 100%` on the image fixed the issue: https://codepen.io/trieloff-the-flexboxer/pen/JqGzXY?editors=1100

**Comment by trieloff** [comment]
I agree that we can simplify, for instance by having fewer break points and fewer image sizes, and should also offer an easier way of customizing the kind of `sizes` value you want, but would not remove the default from the pipeline as it is an effective protection against images that are getting too large.

**Comment by kptdobe** [comment]
We removed the responsifier. Closing then.
