### ISSUE TITLE
log level for embed

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pipeline#321]
an image with a link in `.md` 

```
[![](appstore.png "")](https://itunes.apple.com/us/app/adobe-premiere-rush-cc/id1188753863?mt=8)
```

creates the following warning

```
[hlx] warn: Whitelist forbids embedding of URL: https://itunes.apple.com/us/app/adobe-premiere-rush-cc/id1188753863?mt=8
```

i think not matching the whitelist, should be `debug` at best.

**Comment by tripodsan** [comment]
> i think not matching the whitelist, should be `debug` at best.

and how to do then figure out, why the embed is not working?

**Comment by rofe** [comment]
> why the embed is not working?
The default `EMBED_WHITELIST` only allows `www.youtube.com, spark.adobe.com, unsplash.com/photos`
