### ISSUE TITLE
context dump gets really large and adds a lot of overhead

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#331]
for larger requests, the context dumps of 1 request can get large ( > 20mb). we should add a possibility to disable or avoid large dumps.

**Comment by trieloff** [comment]
I'd keep the dump for the current request in memory and show it only as part of the new error page.

**Comment by tripodsan** [comment]
> I'd keep the dump for the current request in memory and show it only as part of the new error page.

we could also:

- also dump it in case of errors
- always dump it for log-level debug and silly
