### ISSUE TITLE
Add pipeline processing timing information

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#333]
suggest to record the overall and per-step processing time and report in the log and also include in a response header.

https://w3c.github.io/server-timing/#the-server-timing-header-field

eg:
```
Server-Timing: p0;dur=53, p1;dur=47.2, p2;dur=47.2, ....
Server-Timing: total;dur=123.4
```

**Comment by tripodsan** [comment]
Example:
```
Server-Timing: p00;dur=59.755027;desc=fetch ,p01;dur=9.509783;desc=parseMarkdown ,p02;dur=2.042807;desc=parseFrontmatter ,p03;dur=1.459516;desc=find ,p04;dur=6.766895;desc=reformat ,p05;dur=2.553625;desc=split ,p06;dur=4.378436;desc=getmetadata ,p07;dur=1.396577;desc=selectstrain ,p08;dur=1.136908;desc=selecttest ,p09;dur=29.395106;desc=html ,p10;dur=1.238519;desc=undef ,p11;dur=1.79802;desc=transformer ,p12;dur=4.396189;desc=once ,p13;dur=1.45282;desc=setmime ,p14;dur=1.314855;desc=cache ,p15;dur=1.708031;desc=key ,p16;dur=1.558716;desc=debug ,p17;dur=22.07377;desc=tohast ,p18;dur=3.046843;desc=rewrite ,p19;dur=4.639235;desc=addHeaders ,p20;dur=4.207381;desc=stringify ,p21;dur=2.531735;desc=flag ,p22;dur=0.20747;desc=report
Server-Timing: total;dur=217.524699
```

![image](https://user-images.githubusercontent.com/917628/58130831-585e9480-7c1d-11e9-9f33-13cada79d433.png)

**Comment by tripodsan** [comment]
@trieloff @davidnuescheler 

here's the timing of a deployed action:

![image](https://user-images.githubusercontent.com/917628/58132814-9316fb80-7c22-11e9-8054-903051275e5e.png)

**Comment by bdelacretaz** [comment]
There might be a synergy between this and @kptdobe's work on dumping the request sequence in graphical form - being able to drill down from the overall request sequence to the pipeline details as a sequence diagram with timings would be great!
