### ISSUE TITLE
use jsdom throughout the pipeline and use jsdom supporting htl engine

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#337]
once the htl engine supports direct jsdom injection (see https://github.com/adobe/htlengine/issues/62), it should be use in the pipeline.

**Comment by rofe** [comment]
Once that is the case, can we resurrect https://github.com/adobe/htlengine/issues/52? 😬

**Comment by tripodsan** [comment]
> Once that is the case, can we resurrect [adobe/htlengine#52](https://github.com/adobe/htlengine/issues/52)? 😬

yes. we could parse the injected HTML context with JSDOM and then use the dom-purifier on it. but only if JSDOM is enabled - so we need to keep the other sanitizer as well.
