### ISSUE TITLE
<img> gets wrapped by a <p> tag

### ISSUE THREAD

**Issue by anfibiacreativa** [adobe/helix-pipeline#338]
When adding an image to markdown, it gets generated and wrapped by a `<p>` tag. This is not semantic and it's invalid HTML. (It's valid to put a block element inside of another block element. But rendering an empty `<p>` tag with an `<img>` tag inside is not semantic

Suggestion: `<img>` tags generated should not be wrapped by `<p>`

**Comment by ramboz** [comment]
@anfibiacreativa I imagine you mean a plain image as in:

```markdown
![foo](bar.png)
```

should generate:
```html
<img src="bar.png" alt="foo">
```

As opposed to:
```markdown
foo
![bar](baz.png)
qux
```

which would generate:
```html
<p>
  foo
  <img src="baz.png" alt="bar">
  qux
</p>
```

Correct?

> This is not semantic and it's invalid HTML

I would disagree here. The following is definitely valid HTML (and will pass a validator):
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
  </head>
  <body>
    <p><img src="foo" alt="bar"/></p>
  </body>
</html>
```

The `<img/>` tag, according to the spec, is in the _Phrasing Content_ category and as such is a valid single child of a `<p/>` tag. You can also see various use cases of this in the HTML5 spec https://dev.w3.org/html5/spec-LC/embedded-content-1.html#the-img-element

I would also argue that an `<img/>` tag on its own (in HTML5) doesn't have much semantic meaning and should most likely be wrapped in a `<figure/>` element if meant to be used as a block element.

**Comment by anfibiacreativa** [comment]
That's exactly what I meant, yes.

`![foo](bar.png)` 
should generate
`<img src="bar.png" alt="foo">`

Please notice that I clarified that under the HTML5 spec is valid to put a block element inside of another, being both <p> and <img> block elements, it would validate. 
The part of the specification to which you link, correctly describes the use of 

"a phrase or paragraph with an alternative graphical representation: charts, diagrams, graphs, maps, illustrations"
and my interpretation is that those examples are a different usecase than, say, when you have full width image in a stage or hero area, for example.

In those particular cases, and when the image is not part of a textual context, styles for paragraph will cascade to the image or have an impact in its styling that may need to be specifically overwritten (say you add a padding to all paragraphs, you will need to overwrite it to obtain a full width image, which adds specificity and complexity beyond global constraints).

I also would disagree that <img> needs to be wrapped in a <figure> element to be semantic. <figure> is not only meant to wrap images, and <img> in itself clearly describes its purpose, being part of the listed semantic elements in HTML
https://developer.mozilla.org/en-US/docs/Web/HTML/Element

**Comment by ramboz** [comment]
> and my interpretation is that those examples are a different usecase than, say, when you have full width image in a stage or hero area, for example.

Agreed. Now markdown aside, I would probably want to semantically represent hero/stage images as:
```html
<main>
  <header>
    <img src="…" alt="…">
    <h1>My main heading</h1>
  </header>
  <section>
    <header><h2>My 1st section</h2></header>
    <p>Lorem ipsum dolor sit amet <img></p>
    <p>consectetur adipiscing elit</p>
  </section>
  <section>
    <header><h2>My 2nd section</h2></header>
    <p>sed do eiusmod tempor incididunt</p>
    <p><img> ut labore et dolore magna aliqua</p>
  </section>
  <section>
    <header><h2>My 3rd section</h2></header>
    <p>Ut enim ad minim veniam</p>
    <p><img></p>
    <p>quis nostrud exercitation</p>
  </section>
<main>
```

Am I correct, here?

> In those particular cases, and when the image is not part of a textual context, styles for paragraph will cascade to the image or have an impact in its styling

Agreed, and this is a styling problem then, not a semantic one. And from a purely design point-of-view, I can only empathize with the issue. Having something like:
```css
p {
  padding-bottom: 20px;
}
p img {
  vertical-align: bottom;
}
```
would definitely impact my hero image.

I feel that what we are missing is a way to annotate the context of the image to indicate a hero use case vs. a normal inline one and have different HTML renderings for each. Markdown alone usually falls short to convey the various semantic and styling aspects we may need.

For instance, I would probably want to define my hero as:
```markdown
---
type: header
---
![Foo](foo.png)
```
```html
<header>
  <img src="foo.png" alt="Foo">
</header>
```

But have inline images as:
```markdown
---
Lorem ipsum dolor sit amet

![Foo](foo.png)

consectetur adipiscing elit
---
```
```html
<section>
  <p>Lorem ipsum dolor sit amet</p>
  <p><img src="foo.png" alt="Foo"></p>
  <p>consectetur adipiscing elit</p>
</section>
```

And I would probably look at a markdown similar to the following to generate the initial example above:
```markdown
---
type: header
---

![…](…)

# My main heading

---

## My 1st section

Lorem ipsum dolor sit amet ![…](…)

consectetur adipiscing elit

---

## My 2nd section

sed do eiusmod tempor incididunt

![…](…) ut labore et dolore magna aliqua

---

## My 3rd section

Ut enim ad minim veniam

![…](…)

quis nostrud exercitation
---
```

> I also would disagree that <img> needs to be wrapped in a \<figure> element to be semantic. 

I think I failed to convey my meaning here. My point was that the `<img>` alone is probably too generic and would mostly get its semantic meaning from the context it is in.

- `<header><img src="…" alt="…"></header>` => hero image
- `<button><img src="…" alt=""></button>` => button icon (just decorative)
- `<a href="…"><img src="…" alt=""></a>` => link icon (just decorative)
- `<p><img src="…" alt="…"></p>` => inline image
- `<figure><img src="…" alt="…" longdesc="…"></figure>` => figure image used for a diagram or as a descriptive picture
- etc.

Maybe having a clear example of what your whole `md` versus expected `html` looks like would help design a good solution that covers all use cases.

On a side node, we do not directly control how the markdown is parsed at the moment and rely on [remark](https://github.com/remarkjs/remark) for this.

**Comment by trieloff** [comment]
I think we can start by collapsing the paragraph around the image as a first step like this plugin does: https://github.com/remarkjs/remark-unwrap-images#readme

Detecting hero images (or prominent images in general) based on:

- position in the document
- position in the section
- frequency of images in the section

Is a good idea, but should be handled in a separate issue.

**Comment by ramboz** [comment]
@trieloff 

**Do we want to do this for all sole images in any paragraph?**
```markdown
![Foo](foo.png)

![Bar](bar.png)

![Baz](baz.png)
```

```html
<img src="foo.png" alt="Foo">
<img src="bar.png" alt="Bar">
<img src="baz.png" alt="Baz">
```

Note that this breaks the blocks isolation and images are then all inline.

**Do we want to do this for all sole images in single paragraphs in all sections?**
```markdown
![Foo](foo.png)
---
![Bar](bar.png)
---
![Baz](baz.png)

![Qux](qux.png)
```

```html
<section>
  <img src="foo.png" alt="Foo">
</section>
<section>
  <img src="bar.png" alt="Bar">
</section>
<section>
  <p><img src="baz.png" alt="Baz"></p>
  <p><img src="qux.png" alt="Qux"></p>
</section>
```

**Or do we only do it for the "hero" images that are in the 1st paragraph of a section?**
```markdown
![Foo](foo.png)
---
![Bar](bar.png)
---
![Baz](baz.png)

![Qux](qux.png)
```

```html
<section>
  <img src="foo.png" alt="Foo"> <!-- my hero image -->
</section>
<section>
  <p><img src="bar.png" alt="Bar"></p>
</section>
<section>
  <p><img src="baz.png" alt="Baz"></p>
  <p><img src="qux.png" alt="Qux"></p>
</section>
```

**Comment by anfibiacreativa** [comment]
I am very sorry I could not catch up earlier. Thank you for the very detailed description. I agree with you it is a style issue, later in time. But those are the hardest to solve at the time of implementing complex layouts, and would be advisable to contemplate them from the very generation of tags. 

My humble recommendation is to inline images. Generally speaking it's a lot easier to float them, and in general temper with, if they're not wrapped by any other element, like in the first example.

**Comment by trieloff** [comment]
@ramboz 

> Do we want to do this for all sole images in single paragraphs in all sections?

I think this is already covered by https://github.com/adobe/helix-pipeline#contentsections-in-detail `is-only-image`

> Do we want to do this for all sole images in any paragraph?

I'd say there should be only one hero. (This is not a Marvel movie)

> Or do we only do it for the "hero" images that are in the 1st paragraph of a section?

The example looks more like "Or do we only do it for the "hero" images that are in the 1st paragraph of *the 1st* section?"

As we don't reliably know which section will be the first (due to tests and conditions), I'd say no.

Also, detecting the first image in a section or an image that is the first child of a section is very easy in CSS, we don't have to replicate that in the pipeline. One approach to phrase it would be:

The hero image is the first image of the section 
- that is not preceded by more than one heading
- and not preceded by any other paragraph
- and not immediately followed by another image
- and not wrapped in a link

**Comment by anfibiacreativa** [comment]
@trieloff  

> Do we want to do this for all sole images in any paragraph?
> I'd say there should be only one hero. 

What about in the case the intention was to generate a slider with the use of a 3rd party plugin, by targeting the first set of images in the hero area.... Would you reckon they should be wrapped in a <p> tag if it was a set? I imagine that trying to make them full width would result in a lot of specificity.

**Comment by ramboz** [comment]
@anfibiacreativa I think wed go with a list of images in that case, and consider a section with a list that contains only images to be a "gallery". The template can then decide how to render (slideshow, or other alternative).

```mardown
# My awesome page

---

- ![Foo](foo.jpeg)
- ![Bar](bar.jpeg)
- ![Baz](baz.jpeg)

---

Lorem ipsum sic dolor…
```

and the corresponding (minimal) html:
```html
<h1>My awesome page</h1>
<hr>
<ul>
  <li><img src="foo.jpeg" alt="Foo"></li>
  <li><img src="bar.jpeg" alt="Bar"></li>
  <li><img src="baz.jpeg" alt="Baz"></li>
</ul>
<hr>
<p>Lorem ipsum sic dolor…</p>
```

**Comment by davidnuescheler** [comment]
seems to have come back... eg.

```
---

![orangerie-basel.jpg](https://www.designersfactory.com/orangerie/img/orangerie/01.jpg)

---
```
renders to:

```
<div data-hlx-types="has-image nb-image-1 has-only-image" class="hlx-section">
<p><img src="https://www.designersfactory.com/orangerie/img/orangerie/01.jpg" alt="orangerie-basel.jpg"></p>
</div>
```

instead of 

```
<div data-hlx-types="has-image nb-image-1 has-only-image" class="hlx-section">
<img src="https://www.designersfactory.com/orangerie/img/orangerie/01.jpg" alt="orangerie-basel.jpg">
</div>
```
