### ISSUE TITLE
Provide wrap, wrapNodes and classify helper methods

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#354]
Node(s) wrapping and adding css classes are typical operations that any Helix project would need (see https://github.com/adobe/helix-pages/blob/master/src/html.pre.js#L19-L47). We should provide those 3 methods are part of a VDOMHelper class:

* `wrap`: wraps a given set of elements (via a list of elements) inside a new parent
* `wrapNodes`: wraps a given set of elements (via a selector) inside a new parent
* `classify`: add css class name(s) to a given set of elements (via a selector)

**Comment by tripodsan** [comment]
so you want to reimplement https://www.npmjs.com/package/jquery ?

**Comment by kptdobe** [comment]
oh... you mean that I can include jquery in my pre.js ? scary... 
I am going to test that right now... :)

**Comment by tripodsan** [comment]
should work: https://stackoverflow.com/questions/30223265/how-to-use-jquery-with-jsdom5?answertab=active#tab-top

**Comment by kptdobe** [comment]
It is even documented on jquery page: https://www.npmjs.com/package/jquery#node

**Comment by kptdobe** [comment]
Works!

**Comment by kptdobe** [comment]
Using jquery is pretty smooth: https://github.com/adobe/helix-pages/blob/8e717cc27b57001e4b29a87372cdbb7e6808710f/src/html.pre.js#L55-L59

But requires an ugly start point: https://github.com/adobe/helix-pages/blob/8e717cc27b57001e4b29a87372cdbb7e6808710f/src/html.pre.js#L19-L22

Each project would be free to use its preferred library but it must be jsom and npm compatible.

**Comment by tripodsan** [comment]
there is a simpler way, reusing the `defaultView` (aka _window_) of the existing document:
https://github.com/adobe/helix-pages/blob/bb88d856da8560a8f633c6ac38992df028f8bfdf/src/html.pre.js#L27

If we want to promote the use of jquery, I suggest:

- to add `jquery` as dependency to `helix-pipeline` so that it can be used by the scripts
- maybe to add `context.$` ?

**Comment by kptdobe** [comment]
You latest change makes it really easy and simple to use at project level.

I would not add `jquery` as a dependency of the pipeline (at least for now). I would leave it up to the projects to decide (the good old debate about getting rid of jquery client side), maybe there are better frameworks for certain operations you may want to do. `helix-pages` will serve as a good example on how to use `jquery`. Also, if you do not do too complex DOM operations, you can use the DOM API. 

For the record, using `jquery` in `pre.js`: 

In your project folder, run: `npm install jquery`
In your project code, use: 

```
const jquery = require('jquery');
...

function pre(context) {
  const document = context.content.document;
  const $ = jquery(document.defaultView);

  const $divs = $(document).find('div');
  ...
}
```

**Comment by kptdobe** [comment]
Closing this issue since we will not provide those default helper functions.

**Comment by tripodsan** [comment]
> I would not add `jquery` as a dependency of the pipeline (at least for now). I would leave it up to the projects to decide (the good old debate about getting rid of jquery client side), maybe there are better frameworks for certain operations you may want to do.

the problem is, that you the need to add a `package.json` which I think should not be needed out-of-the-box.

@trieloff WDYT?

**Comment by kptdobe** [comment]
But out-of-the-box, do you need to re-wrap you divs ? ;)

**Comment by tripodsan** [comment]
> But out-of-the-box, do you need to re-wrap your divs ? ;)

;-)

ok. let's keep it out at the moment...

**Comment by trieloff** [comment]
Being able to use `jquery` is nice. Having `jquery` in your dependency tree by default isn't.
