### ISSUE TITLE
Inject frontmatter properties of a section as DOM properties

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#355]
Once https://github.com/adobe/helix-pipeline/issues/279 is done, sections will be included by default inside a wrapping element (`div` or `section`, being discussed). Leveraging the frontmatter properties of each section and injecting them as DOM properties would be an easy way for a developer to give some styling freedom but also directive to control the section rendering to content authors.

Example:

```
---
class: my-custom-section-class
data-some-custom-data: my-value
---
section content
```

would lead to a wrapping DOM element:

```
<div class="section my-custom-section-class" data-some-custom-data="my-value"><p>section content</p></div>
```

cc @davidnuescheler

**Comment by ramboz** [comment]
I'd also propose to let the author specify the tag to be use:
```yaml
tag: my-tag
class: my-custom-section-class
data-some-custom-data: my-value
```
to get:
```html
<my-tag class="section my-custom-section-class" data-some-custom-data="my-value"> 
    <p>section content</p>
</my-tag>
```
The idea is really just to be able to better control semantics and SEO

**Comment by davidnuescheler** [comment]
looking through the PR i think we have gone a little bit beyond the above example provided by @ramboz 

i really liked what's outlined and i think as we start thinking of the DOM as becoming the more central payload for the pipeline, i think it is desirable to pass information that we want to use throughout processing along as attributes (or tags) in the DOM, even if they get removed in a final step before the markup is generated. 

in that light i think that we could allow non-standard attributes and tags throughout the pipeline as we give the developer the ability to enforce strict compliance at the end of the pipeline if they want to.

**Comment by ramboz** [comment]
Should be mostly covered by #379 now and in since [v4.0.0](https://github.com/adobe/helix-pipeline/tree/v4.0.0)
