### ISSUE TITLE
Disable XSS sanitizer by default

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#356]
Allowing HTML in markdown voids the need to a XSS sanitizer a little bit.
Suggest to disable it by default. either by removing it from the html pipeline completely, or safeguard it with:

```
    .before(sanitize).when(paranoid)
```

/cc @trieloff @davidnuescheler @ramboz

**Comment by rofe** [comment]
Agreed. And having to remember to use
```js
  ${content.document.body.innerHTML @ context = 'unsafe'}
```
in `html.htl` is error prone and kind of ugly...

**Comment by tripodsan** [comment]
> Agreed. And having to remember to use
> 
> ```js
>   ${content.document.body.innerHTML @ context = 'unsafe'}
> ```
> 
> in `html.htl` is error prone and kind of ugly...

this is reverted with the new htlengine https://github.com/adobe/helix-cli/pull/917
