### ISSUE TITLE
Update secrets schema

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#360]
@trieloff shouldn't `HLX_SANITIZE_DOM` also be added to https://github.com/adobe/helix-pipeline/blob/master/src/schemas/secrets.schema.json?

_Originally posted by @rofe in https://github.com/adobe/helix-pipeline/pull/358_

Yes. Yes, it should.

**Comment by rofe** [comment]
I suggest we remove the `HLX_` prefix, because none of the other secrets in the schema have it.
