### ISSUE TITLE
Add `context.content.data` or allow additional properties in `context.content` 

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#378]
The current pipeline context doesn't allow to pass "custom" data between the pipeline functions.

This is currently a problem of the helix `pre.js` functions that wish to pass some data to the HTL scripts. the current workaround is to cleanup after the HTL is executed: https://github.com/adobe/helix-cli/blob/5222277edc96fe1cf6adc8f117f747ab62f28cd1/src/parcel/OutputTemplate.js#L22-L37

### Suggestion A:

Allow additional properties in `context.content`.

### Suggestion B:

Add a `data` object to `context.content`, and/or to `context`:

```
  "$id": "https://ns.adobe.com/helix/pipeline/content",
  ...
    "data": {
      "type": "object",
      "description": "Custom object that can hold any user defined data.",
    }
```

@trieloff WDYT?

**Comment by tripodsan** [comment]
@trieloff thanks for the 👍, but what should it be: **A** or **B** ?

**Comment by trieloff** [comment]
B
