### ISSUE TITLE
Wrong HTML rendering with lists

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#458]
the following lists are rendered correctly in github:

```
## Then numbered lists:
1. First install the dependencies:  
`$ npm install`
1. Bar **bold**
1. Fruits
    1. Apple
    1. Oranges
    1. Lemons
        1. Roman
        1. Greek  
Muiltiline  
With `code`.
        1. Spanish
```

## Then numbered lists:
1. First install the dependencies:  
`$ npm install`
1. Bar **bold**
1. Fruits
    1. Apple
    1. Oranges
    1. Lemons
        1. Roman
        1. Greek  
Muiltiline  
With `code`.
        1. Spanish

--- 

but the pipeline produces:

<h2 id="then-numbered-lists">Then numbered lists:</h2>
<ol>
<li>First install the dependencies:<br>
<code>$ npm install</code></li>
<li>Bar <strong>bold</strong></li>
<li>Fruits
1. Apple
1. Oranges
1. Lemons
1. Roman
1. Greek<br>
Muiltiline<br>
With <code>code</code>.
1. Spanish</li>
</ol>

**Comment by tripodsan** [comment]
another example:

```
### **Demos**
You can watch the entire recording here
1. Server timing & DOM based HTL engine
1. Helix Pages & auto-generated sequence diagrams
1. Performance analysis of Helix OpenWhisk actions
1. Authoring user journey
1. Dev experience: Helix 6 months ago and today
```

### **Demos**
You can watch the entire recording here
1. Server timing & DOM based HTL engine
1. Helix Pages & auto-generated sequence diagrams
1. Performance analysis of Helix OpenWhisk actions
1. Authoring user journey
1. Dev experience: Helix 6 months ago and today

---
pipeline:

<p>You can watch the entire recording <a href="https://bluejeans.com/s/elM6g/">here</a>.
1. Server timing &amp; DOM based HTL engine (@tripodsan)
1. Helix Pages &amp; auto-generated sequence diagrams (@ktpdobe)
1. Performance analysis of Helix OpenWhisk actions (@dunguyen)
1. Authoring user journey (@kamendola)
1. Dev experience: Helix 6 months ago and today (@anfibiacreativa)</p>

**Comment by derekneuland** [comment]
I'll take this!

**Comment by derekneuland** [comment]
Can you point me in the right direction to which file should be edited?

**Comment by MarquiseRosier** [comment]
@derekneuland I can help you :)  were you able to reproduce the issue?

**Comment by MarquiseRosier** [comment]
There's a few ways to reproduce. You can use the helix-cli demo, You can follow the instructions in the helix-cli Readme at https://www.github.com/adobe/helix-cli

You'll learn how to create a demo project. 

Plug the code that's giving erroneous output; into your demo's markdown project, 
then run hlx up --local-repo <root of your demo dir> --dev-default HTTP_TIMEOUT 3000

This should reproduce the error.

Or 

you can even; take the markdown that's giving the bad result and plug it into one of the tests in https://www.github.com/adobe/helix-pipeline

From there it's just a matter of debugging and breaking to see where in the pipeline might dictate how an md element gets rendered!

**Comment by lex111** [comment]
I did some investigation, current issues can be solved, but links with spaces (because is that link is not a valid markdown link) and links references (because [this bug in the remark](https://github.com/remarkjs/remark/issues/324)) will stop working. :confused:

**Comment by tripodsan** [comment]
@derekneuland / @lex111  Still working on this?

**Comment by lex111** [comment]
@tripodsan I'm stuck :(

**Comment by MarquiseRosier** [comment]
I'll take this; @lex111 unless you're still open to working on it. 

@lex111 hey you referenced an issue with link parsing; what did you find? 

@tripodsan I'm starting to think this is an issue with how remark-parse handles lists; I'm going to do some more investigating

**Comment by MarquiseRosier** [comment]
@lex111 

This is related to; it's unresolved: they're making up a fix :) 
https://github.com/remarkjs/remark/issues/315

**Comment by lex111** [comment]
@MarquiseRosier cool, unfortunately I gave up, but hope this issue will be resolved soon.

**Comment by MarquiseRosier** [comment]
Hey folks! Looks like this is about to be fixed!! :) 

https://github.com/remarkjs/remark/issues/315#issuecomment-702207738

By PR: 
https://github.com/remarkjs/remark/pull/536

**Comment by trieloff** [comment]
Cool, and scary, as this will probably break a few other things for us.

**Comment by tripodsan** [comment]
won't fix.
