### ISSUE TITLE
Embeds do not work in "production"

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#461]
1. Run `hlx demo && cd demo`
1. Create a `foo.md` file and insert some content
1. Insert `` `markdown:foo.md` `` or `` `markdown:/foo.html` `` inside `index.md` of a project.
1. Add a `embed_html.htl` script to the project with content: `${content.document.body}` (just dump the body of the embedded document)
1. Run `hlx deploy` and `hlx publish` of the project
1. Open the "production" site: embeds not present

Quick debugging shows that generated esi include do not have the extension: `<esi:include src=\"/t.embed.\">`
This works locally with `hlx up`

**Comment by tripodsan** [comment]
looks like an old helix-pipeline / htlengine is used for production

**Comment by rofe** [comment]
Resolved with https://github.com/adobe/helix-simulator/issues/292
