### ISSUE TITLE
icon support

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pipeline#500]
it would be great if helix pages supported icons from an svg symbol sprite file.

i would probably for the time being propose that there is a fixed `/icons.svg` file and something like `:twitter:` gets translated to

```
<svg class="icon twitter"><use xlink:href="/icons.svg#twitter"></use></svg>
```

**Comment by rofe** [comment]
> The latter lib seems to be already doing exactly what we want. All we need is a sample icons.svg...

Ah no, this is only converting emojis, never mind :)

**Comment by tripodsan** [comment]
for simplicity, let's create a pipeline step **iconizer** that transforms `:([a-zA-Z0-9_])+:`  to `<img src="/icons/$1.svg" />`

**Comment by rofe** [comment]
After discussing with @trieloff, I'm implementing an approach with `/icons` folder and individual SVGs at first, which seems easier to manage. Later on, we could still add logic using an `/icons.svg` if present.
