### ISSUE TITLE
Generate `Link` header with `as` attribute. 

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-pipeline#520]
A `Link` response header is automatically generated from `<link />` tags (see #122). However, only `href` and `rel` attributes are handled. The `as` attribute is ignored. 

See:
https://www.w3.org/TR/preload/#as-attribute
https://html.spec.whatwg.org/multipage/semantics.html#attr-link-as

**Comment by stefan-guggisberg** [comment]
Further investigation revealed:

- The `preload` keyword used in with `link` elements is W3C Candidate Recommendation from 26 June 2019 and work in progress: https://www.w3.org/TR/preload
- `JSDOM` does not yet support the `as` attribute specified in above document.

I suggest we wait until JSDOM supports the additional `link` attributes. As a workaround we probably could use something like `<meta http-equiv="Link" content="rel=preload href=&quot;/some.jpeg&quot; as=image" />`

**Comment by trieloff** [comment]
Or we could have a mapping 
* `link rel=stylesheet` = `as=style`
* `img` = `as=image`
* `script src` = `as=script`
* `script type=module` = `as=script`

and so on: https://www.w3.org/TR/preload/#as-attribute

**Comment by stefan-guggisberg** [comment]
> Or we could have a mapping

good point. but then we loose control what we want to push. automagic vs explicit, I lean towards explicit.

**Comment by trieloff** [comment]
Is there a JSDOM issue for the `as` attribute? Maybe the fastest path to getting proper support is a PR and we would benefit from having that relationship with the JSDOM team anyway.

**Comment by stefan-guggisberg** [comment]
> Is there a JSDOM issue for the `as` attribute? 
https://github.com/jsdom/jsdom/issues/2471

**Comment by stefan-guggisberg** [comment]
With the changes in ad22823 the `as` attribute will be handled once JSDOM supports it.
