### ISSUE TITLE
slow response for relatively simple .md

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pipeline#583]
requesting https://theblog-davidnuescheler.hlx.page/tools/tagger/tags.plain.html which should produce a simple nested html list from this `.md`
https://raw.githubusercontent.com/davidnuescheler/theblog/master/tools/tagger/tags.md produces a response time that is much slower than expected.

**Comment by tripodsan** [comment]
it seems that the vdom generation is slow:

```
parse: 98.900ms
vdom: 19330.442ms
```

**Comment by tripodsan** [comment]
problem was extensive use of `selectAll()` in VDOM matching. improved version:

```
parse: 98.240ms
vdom: 133.237ms
```
