### ISSUE TITLE
Inject Default Metadata from frontmatter.yaml

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#607]
When rendering `/foo/bar.md`, in addition to fetching `/foo/bar.md` also `/foo/frontmatter.yaml` should get fetched.

The contents of `frontmatter.yaml` should be merged with `content.section[0].meta` so that `frontmatter.yaml` never overrides existing scalar types and appends to existing arrays.

This will enable the creation of folder-specific metadata.

For this to work across the board, we need to adjust the word and google docs adapters to either serve YAML directly or to convert simple spreadsheets into YAML, so that metadata can be managed in spreadsheets.

/cc @davidnuescheler 
---

Discussion: this would be an alternative or additional approach to #606 but come at the cost of making one additional, speculative request in `fetch`. With the new Downloader, we can defer `await`ing the actual download until the `meta` step (there are 6 other steps in between), so the risk of the rendering actually being delayed due to the additional request is tiny.

**Comment by tripodsan** [comment]
won't fix
