### ISSUE TITLE
Downloader should forward a list of predefined headers

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#612]
When helix-pipeline action is invoked, some headers (especially request tracking headers) are key and should be forwarded to any other invoked action (see https://github.com/adobe/helix-home/issues/70).

The Download is now responsible to "fetch" / request content from other action, it should be responsible to forward those headers. `X-CDN-URL`, `X-Request-Id` and `X-CDN-Request-Id` are the initial candidates.

**Comment by tripodsan** [comment]
^^^ fix commit message `feat` -> `feat`
