### ISSUE TITLE
default timeout of 10s too low for external sources

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#638]
**Is your feature request related to a problem? Please describe.**
the default timeout to fetch external sources, like word2md is 10s. which is often too slow, especially for cold starts.

**Describe the solution you'd like**
set the default to 20s and make it configurable.

**Comment by trieloff** [comment]
The timeout is already configurable: https://github.com/adobe/helix-pipeline/blob/master/docs/secrets.md#HTTP_TIMEOUT

Can't we use the double timeout for `word2md` and co and keep the default timeout for raw?

**Comment by tripodsan** [comment]
> Can't we use the double timeout for `word2md` and co and keep the default timeout for raw?

currently, we use 10s for the externals, and 1s for default github resources. so we would need a 20x timeout for the external requests.

**Comment by trieloff** [comment]
Ok.
