### ISSUE TITLE
npm tests fail when offline

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#64]
the npm tests read github to tests the markdown parsing. when working offline, the tests fail.

**Comment by trieloff** [comment]
Would you rather:
- mock GitHub
- exclude tests with network activity from unit testing?

**Comment by tripodsan** [comment]
Why not use replay?

**Comment by trieloff** [comment]
Ok, so we just mock it using Replay. Makes the tests more robust to content changes in that repo, too.

**Comment by trieloff** [comment]
I found another way: we can check for connectivity, and skip the test when offline.

**Comment by kptdobe** [comment]
Just tested, tests work offline.
