### ISSUE TITLE
Pipeline v6.10.0 breaks some project deployments

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#642]
Appeared via the helix-pages integration tests: https://github.com/adobe/helix-pages/pull/212

Deployed helix-page project fires an 500 for each page request.

Initial debugging session reveal runtime execution error: 

```
"error": "Initialization has failed due to: Error: Cannot find module './utils/common'\n    at webpackEmptyContext (/nodejsAction/XXEKhcLL/html.js:273252:10)\n    at /nodejsAction/XXEKhcLL/html.js:272965:14\n    at define (/nodejsAction/XXEKhcLL/html.js:272958:20)\n    at Object.<anonymous> (/nodejsAction/XXEKhcLL/html.js:272962:1)\n    at Object.Array.concat.webpackEmptyContext.keys (/nodejsAction/XXEKhcLL/html.js:273245:30)\n    at __webpack_require__ (/nodejsAction/XXEKhcLL/html.js:30:30)\n    at Object.Array.concat.define (/nodejsAction/XXEKhcLL/html.js:272802:16)\n    at __webpack_require__ (/nodejsAction/XXEKhcLL/html.js:30:30)\n    at Object.Array.concat.setdefault.setdefault (/nodejsAction/XXEKhcLL/html.js:224335:37)\n    at __webpack_require__ (/nodejsAction/XXEKhcLL/html.js:30:30)"
```

This seems to come from newly added npm dependency `emmet`: https://github.com/emmetio/emmet/blob/v1.6.3/lib/emmet.js#L10

`emmet` does not seem to be webpack friendly: https://github.com/emmetio/emmet/issues/516

Recommandation is to use https://www.npmjs.com/package/@emmetio/expand-abbreviation instead. Based on @ramboz, this is all we need anyway.

**Comment by kptdobe** [comment]
Working on resolution with @ramboz

**Comment by kptdobe** [comment]
Here is a status: several things are broken but all related.

- current `npm run test` in `helix-cli` fails because of pipeline v6.10.0 (basically, what's in `master`)
- running the tests with previous pipeline version (v6.9.6) works: `env HLX_CUSTOM_PIPELINE='https://github.com/adobe/helix-pipeline.git#v6.9.6' npm run test`
- running the tests with current proposed PR still fails: `env HLX_CUSTOM_PIPELINE='https://github.com/adobe/helix-pipeline.git#issues/642' npm run test` - maybe the tests must be adjusted, a lot of recordings seem to fail
- on top of that, I discovered why we ended here: the smoke tests do not run `helix-cli` with the provided pipeline, they always test with the latest one - i.e. if you work in a pipeline branch, it is not tested. That's why we did not see the current failure but we see it now in CircleCI. This is being addressed here: https://github.com/adobe/helix-continuous/issues/80

**Comment by kptdobe** [comment]
I merged the changes for adobe/helix-continuous#80, tests running on the #644 branch are now the correct ones. And they are failing: https://circleci.com/workflow-run/80a1075f-d8b8-433f-b1fb-7905e23b11ca

**Comment by ramboz** [comment]
I'll take care of fixing the tests in #644

**Comment by kptdobe** [comment]
I just saw https://github.com/emmetio/expand-abbreviation is deprecated and moved to https://github.com/emmetio/emmet which either v2.0 is RC (for 8 months now) or latest release is v1.6.3 which is 3 years old and not webpack friendly.
Do we really need `emmet` ?

**Comment by ramboz** [comment]
@kptdobe Well, it is a well-established standard for quick selectors. Front-end devs are used to the notation since "zen coding" started.

So it's a bummer that emmet doesn't work because of webpack, but emmet-abbreviation is deprecated.
