### ISSUE TITLE
investigate why requests are not concurrent

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#664]
![image](https://user-images.githubusercontent.com/917628/78961336-120f6e00-7b2c-11ea-8658-92116dc8b534.png)

why is the 2nd request to raw.github (`helix-markup.yaml`) AFTER the word2md? 
It should be parallel to fetching the fstab.yaml

**Comment by trieloff** [comment]
https://github.com/adobe/helix-pipeline/blob/4489463b5e0a2d36e8c770c74d8da71a6a006826/src/defaults/html.pipe.js#L68-L70

If we swap `fetchExternal` and `fetchMarkupConfig`, it should work in parallel, as `fetchFstab` and `fetchMarkupConfig` are non-blocking, but `fetchExternal` is blocking.

**Comment by stefan-guggisberg** [comment]
@tripodsan Can this issue be closed?

**Comment by tripodsan** [comment]
yup.
