### ISSUE TITLE
Forward Extra Logging Header in Downloader

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#676]
From @mcorlan:

> - By default, successful blocking invocations will not produce an activation record, thus running "wsk activation list" will not list any of these. Logs are still recorded and can be retrieved using the activation ID  - this is still being sent to the client invoking the action
> - Developers can force creating an activation record for successful blocking invocations by including this header `X-OW-EXTRA-LOGGING: on` in the request

See also:
- https://github.com/adobe/helix-publish/issues/403
- https://github.com/adobe/helix-dispatch/issues/232

we should make sure that this header is passed on in all Runtime requests `Downloader` is making.

**Comment by tripodsan** [comment]
any particular reason why you want to keep the activation records?

**Comment by trieloff** [comment]
https://github.com/adobe/helix-dispatch/issues/232#issuecomment-613898446

**Comment by tripodsan** [comment]
right, but only if `X-DEBUG` is set.

**Comment by trieloff** [comment]
I don't think we need to double check. `X-OW-EXTRA-LOGGING` will be set only in two cases:

1. you are requesting the `html` action directly and set the header using `curl`, i.e. you know what you are doing
2. you called Fastly with `X-Debug`, which called `dispatch` with `X-OW-EXTRA-LOGGING`, which passed it on to pipeline.

**Comment by tripodsan** [comment]
ah... you mean forward!

**Comment by tripodsan** [comment]
won't fix.
