### ISSUE TITLE
Resilience: FrontMatter is too strict

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#697]
I was authoring a markdown file (stored in onedrive but I think this does not really matter) and I somehow forgot some line breaks around the sections breaks:

```
# Multimedia Test
---
![](https://hlx.blob.core.windows.net/external/20f9d6dff67514da262230822bda5f3b50ef28c6#image.png)
---
PUBLISHED ON 28-04-2020
---

### SoundCloud

<https://soundcloud.com/adobeexperiencecloud/experience-makers-in-travel-and-hospitality>

### YouTube

<https://www.youtube.com/embed/L8YPmZ6jYyQ?rel=0>

### SlideShare

<https://www.slideshare.net/adobe/adobe-digital-insights-holiday-recap-2019>

---
Topics: Bar, Baz
Products: Stock, Creative Cloud
```

This fires a 500 (via helix-pages):

```
Exception during #05/use:parseFrontmatter from /nodejsAction/XXKFHkjA/html.js:225207: TypeError: Cannot read property 'idx' of null at map (/nodejsAction/XXKFHkjA/html.js:257850:17) at map (/nodejsAction/XXKFHkjA/html.js:4047:11) at map.next (<anonymous>) at filter (/nodejsAction/XXKFHkjA/html.js:4065:14) at filter.next (<anonymous>) at flat (/nodejsAction/XXKFHkjA/html.js:4296:16) at flat.next (<anonymous>) at trySlidingWindow (/nodejsAction/XXKFHkjA/html.js:4552:14) at trySlidingWindow.next (<anonymous>) at filter (/nodejsAction/XXKFHkjA/html.js:4065:14)
```

This also triggered an escalation because of too many 5xx errors.
Adding some few line breaks here and there fixed the issue.

This is not a good user-experience and I am sure there is a way to pre-process the md before the mdast transformation to add the missing required line breaks for me and avoid those errors while authoring.

**Comment by trieloff** [comment]
@kptdobe you should try if this issue exists here too: https://github.com/adobe/helix-pipeline/pull/685 

If no, then an approving PR is all we need to fix it. If yes, then @tripodsan has another edge case to consider.

Just some background

```markdown
PUBLISHED ON 28-04-2020
---
```

could be a headline or just the end of a section.

**Comment by trieloff** [comment]
In any case, this should not break, and throw a 500, even if it is confusing to the pipeline.

**Comment by tripodsan** [comment]
I'll take a look and fix it in the plugin

**Comment by tripodsan** [comment]
I added the case to the tests and it passes.
