### ISSUE TITLE
Support Vimeo embeds

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#702]
See https://theblog.adobe.com/slow-down-and-speed-up-clips-in-premiere-rush/.

Required for https://github.com/adobe/theblog/issues/186

**Comment by kptdobe** [comment]
> I couldn't find the exact video URLs

I think that's a general issue, it seems that you can export the video and only get the player url. For Soundcloud, I had the same issue that I solved by requesting the player url and extract the direct url from the dom meta (see https://github.com/adobe/helix-theblog-importer/blob/master/src/index.js#L44-L64)

Video does not provide the "direct" url. See https://player.vimeo.com/video/349091463

One option would be to keep the player url and `helix-embed` would be able to deal with it.
WDYT ?

**Comment by trieloff** [comment]
I created a private video (only visible for people who have the URL), copied the URL in Vimeo and it still works: https://adobeioruntime.net/api/v1/web/helix/helix-services/embed@v1/https://vimeo.com/415498678/5349aa3e1f – so for private videos I think authors will be able to still share and embed them.

**Comment by kptdobe** [comment]
For the import, it is more the other way around: we only have the player url, I can use it for the embed but then it does not work: https://adobeioruntime.net/api/v1/web/helix/helix-services/embed@v1/https://player.vimeo.com/video/349091463

**Comment by kptdobe** [comment]
My proposal is to make helix-embed smarter and use the player url as is if this is the one provided.

**Comment by MarquiseRosier** [comment]
{
        "s": "^https?:\\/\\/player\\.vimeo\\.com\\/video\\/(\\d+)",
        "m": "i"
    },

This is on the list actually!
