### ISSUE TITLE
Move image handler into pipeline step before "meta"

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pipeline#706]
Helix Pages now uses `context.content.image` in the metadata, but in case of Azure blob store images it unfortunately doesn't contain the `/hlx_*` URL.

@tripodsan suggested to move the image handler, which is currently rewriting blob store links on the VDOM as part of the "html" step, into its own "image" step and insert it before "meta", so the image URLs are already rewritten in the mdast when metadata is being extracted.

**Comment by rofe** [comment]
An alternative approach would be to move the "meta" step after the "html" step (thereby slightly breaking the extension point API) and extract the metadata from the VDOM.

**Comment by tripodsan** [comment]
@trieloff was there a specific reason you added the image-helixalizer as part of the mdast->VDOM transformation and not as an operation on the mdast ?

**Comment by trieloff** [comment]
If I remember correctly, you said that you wouldn’t do this in word2md, so that the markdown would stay consistent. I might have concluded that this was a transformation that is specific to the HTML conversion.

We can still pull this out into a separate pipeline step.

**Comment by tripodsan** [comment]
> If I remember correctly, you said that you wouldn’t do this in word2md,

yes. not in word2md. 

we could:
- add it as extra step, operating on the VDOM
- move the get-metadata after the html transformation and make it work on vdom

**or**
- add it as extra step, but operate on mdast
- move it before the get-metadata step

**Comment by tripodsan** [comment]
> I might have concluded that this was a transformation that is specific to the HTML conversion.

Right. But all other 'special' operations are individual steps.

**Comment by trieloff** [comment]
I very much prefer your second option.

- MDAST is cleaner than HTML
- Metadata detection works on MDAST and I wouldn't want to port it to working on HTML

**Comment by tripodsan** [comment]
> second option.

?

**Comment by trieloff** [comment]
> **or**
> 
> - add it as extra step, but operate on mdast
> - move it before the get-metadata step

^^ that *second* option

**Comment by rofe** [comment]
Or the one already mentioned in the description ^^ 😉
