### ISSUE TITLE
Rendering a table with 5.7k rows triggers a 504

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#718]
Follow up issue once https://github.com/adobe/helix-pipeline/issues/714 is solved.

Open https://hlxsite-kptdobe.hlx.page/test.html -> 504.

**Comment by kptdobe** [comment]
Here are the logs for one failing activation:

```
wsk activation get ce5f42d86f87443d9f42d86f87043dc1
{
    "namespace": "helix-pages",
    "name": "html",
    "version": "0.0.2",
    "subject": "helix-pages",
    "activationId": "ce5f42d86f87443d9f42d86f87043dc1",
    "start": 1589457045107,
    "end": 1589457057990,
    "duration": 12883,
    "statusCode": 0,
    "response": {
        "status": "action developer error",
        "statusCode": 0,
        "success": false,
        "result": {
            "error": "The action did not produce a valid response and exited unexpectedly."
        }
    },
    "logs": [],
    "annotations": [
        {
            "key": "path",
            "value": "helix-pages/9a5a82c7da7b467aec1622039e386f13a4af81e2/html"
        },
        {
            "key": "waitTime",
            "value": -153
        },
        {
            "key": "kind",
            "value": "nodejs:10"
        },
        {
            "key": "timeout",
            "value": false
        },
        {
            "key": "limits",
            "value": {
                "concurrency": 200,
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        }
    ],
    "publish": false
}
```

It seems to always fail after 12s. Maybe a 10s timeout... But things work locally. Need more debugging.

**Comment by tripodsan** [comment]
maybe it goes out of memory?

**Comment by kptdobe** [comment]
How can I find this info ? And if so, how can I solve this ? :)

**Comment by trieloff** [comment]
You could deploy the action with a higher memory limit. If that works, you have fix and likely reason confirmed in one.

**Comment by tripodsan** [comment]
> How can I find this info ? And if so, how can I solve this ? :)

you can measure the memory consumption locally. @stefan-guggisberg did some tests with the qr-code lib...maybe he has some tips.

otherwise add something like:
https://github.com/adobe/helix-gdocs2md/blob/master/src/action-status.js

but the important value is:

```
const memInfo = process.memoryUsage().rss;
```

**Comment by stefan-guggisberg** [comment]
Unfortunately there's no way to handle a situation where your own process goes OOM. A `JavaScript heap out of memory` error is always fatal and can't be caught/logged. 

What you could try (not sure if it's possible in the I/O Runtime env though): 

Fork a child process and run the memory intensive task in the child process. The parent process gets notified if the child process e.g. runs OOM. This way you can handle the error gracefully and log it appropriately.

**Comment by tripodsan** [comment]
@stefan-guggisberg you wrote recently, that you analyzed the heap consumption of the qr-code decoder. how did you do this?

**Comment by stefan-guggisberg** [comment]
@tripodsan I ran QR decoding in batches of different sizes (e.g. 100 images) and logged memory stats (`process.memoryUsage()`) before and after. Finally I ran `gc()` and logged the stats again.

**Comment by kptdobe** [comment]
I doubled the action memory limit (256 -> 512) and this fixes the issue.
I'll create a PR for helix-cli.

**Comment by tripodsan** [comment]
won't fix.
