### ISSUE TITLE
Support authenticated GitHub access

### ISSUE THREAD

**Issue by stevengill** [adobe/helix-pipeline#72]
This will be needed eventually for pre-release content and other private code we want to share.

From @trieloff:

1. https://github.com/adobe/hypermedia-pipeline/blob/master/src/html/fetch-markdown.js needs to be adjusted to make authenticated requests to GitHub using credentials that are provided as parameters.

2. We need to find a way to pass the parameters. A simple first step would be to just pass them as default params to the action in `helix-cli` (you would need to create a personal API token in the GitHub UI)

We might also want to eventually support GitCorp repos as well. 

This issue covers making Github requests using the provided `GITHUB_TOKEN`.

**Related issues** 
 - adobe/helix-cli#901 (`hlx publish --github-token`)
 - adobe/helix-publish#165
 - adobe/helix-pipeline#72 
 - adobe/helix-dispatch#71
 - adobe/helix-resolve-git-ref#1
 - adobe/helix-static#46

**Comment by rofe** [comment]
Tracked in https://github.com/adobe/helix-cli/issues/912

**Comment by trieloff** [comment]
There is a cli part to this (passing the token to Fastly or the action) and a pipeline part (using the token in the request). This issue should track the pipeline part.
