### ISSUE TITLE
youtube image style embed breaks local rendering

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-pipeline#720]
**Description**
UPDATE: I tracked the issue down the helix-cli's HelixServer

@davidnuescheler discovered an issue with local development, 
The following markdown fails: 
```
There has to be a better way. Luckily, there is with [Adobe Scan](https://acrobat.adobe.com/us/en/mobile/scanner-app.html).

![](https://www.youtube.com/embed/9yFOAkINRp8)

With the free Adobe Scan app, she can easily convert multi-page handwritten schoolwork into a single, high-quality PDF. Scan works hard behind the scenes to identify and sharpen handwritten text and remove distracting elements you don’t want, like glare or shadows. Scans can be reordered, renamed, and submitted to any portal being used by the school, or added to Google Drive, Dropbox, or an email.
```
The html isn't rendered beyond the image style embed 

**To Reproduce**
clone the blog repository at https://github.com/adobe/theblog
cd into theblog local repo
and run hlx up
Now test sites with youtube embeds, like http://localhost:3000/en/drafts/migrated/2020/04/29/10-brands-that-shifted-their-advertising-strategy-amid-covid-19.html

and http://localhost:3000/en/drafts/migrated/2020/04/29/adobe-scan-is-the-new-homework-lifehack.html

**Expected behavior**
A link should appear instead and the rest of the markdown should be rendered and displayed

**Actual behavior**
<img width="1680" alt="Screen Shot 2020-05-14 at 1 28 20 PM" src="https://user-images.githubusercontent.com/12217245/81982518-d06c5a00-95e6-11ea-82ae-bd0b22f43681.png">

**Version:**
9.1.8

**Additional context**
I suspect it's related to the Edge Side Include snippets.

**Comment by rofe** [comment]
I ran into the same here, too:
http://localhost:3000/en/drafts/migrated/2020/04/27/the-state-of-utah-uses-adobe-sign-to-accelerate-telework-during-crisis.html

**Comment by MarquiseRosier** [comment]
@rofe thanks for this other example! I think this has to do with an unclosed div tag! I think this is enough to break it locally, i'm looking for a why, if you have some reasoning please provide it :D
