### ISSUE TITLE
Sections trigger ambiguous frontmatter fence error

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pipeline#721]
**Description**
As of late, the pipeline's frontmatter parser complains about empty lines after `---`. Actually, that's exactly how we used to define *Sections* in our documents 😄 - and luckily that still works.

**To Reproduce**
I ran into it while developing on [theblog](https://github.com/adobe/theblog), but you can reproduce it by just adding the following markdown file in your local dev env and requesting it:
```md
# Title

---

Lorem ipsum 1

---

Lorem ipsum 2

---

Lorem ipsum 3
```

**Expected behavior**
No complaints when `---` is followed by an empty line

**Actual behavior**
```
Error: Found ambiguous frontmatter fence: Block contains empty line! Make sure your mid-document YAML blocks contain no empty lines and your horizontal rules have an empty line before AND after them. Lorem ipsum 1
```

**Version:**
helix-pipeline 7.1.3

**Comment by rofe** [comment]
I find it still quite picky to be honest... there's a lot of log output for what seems to be markdown with valid sections. Maybe it should not consider three dashes followed by an emtpy line as frontmatter at all?

```md
---

## Foo
```
triggers
```sh
[hlx] info: Found ambiguous frontmatter fence: Block contains yaml key not starting with a letter. If this was intended, escape the key with quotes. 
```
And 
```md
---

-   <https://www.foo.bar>
```
triggers
```sh
[hlx] warn: Error: Found ambiguous frontmatter block: Block contains valid yaml, but it's data type is function Array() { [native code] } instead of Object.Make sure your yaml blocks contain only key-value pairs at the root level!
```

**Version:**
helix-pipeline 7.2.0

**Comment by tripodsan** [comment]
let's ignore then those, too....
