### ISSUE TITLE
Change externals resolution priority to github-first

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#726]
**Is your feature request related to a problem? Please describe.**
In a helix-pages project, where an external source provider is mounter to `/`, it is expensive to try to load `head`, `header` and `footer` from the external. 

**Describe the solution you'd like**
there is probably no good reason, why a content author editing word/gdocs would need to overwrite a file in github. 

The priority of resource loading should be switched around:

1. try loading markdown from github
2. try loading markdown from external source (if fstab matches, etc...)

**Comment by trieloff** [comment]
Just FYI `helix-content-proxy` does not have any fallback mechanism right now and we would need to implement one.

**Comment by tripodsan** [comment]
closing for now since content proxy is used.
