### ISSUE TITLE
enable helix-run-query data embeds

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-pipeline#730]
add run_query to to data_embed_whitelist

**Comment by trieloff** [comment]
That will need to look a bit different than the rest of the whitelist, as the whitelist is a domain filter. I'd probably tweak the function that checks if a URL is on the whitelist and have the `_run_query` pattern hardcoded.

Or: we come up with a way to interpret the domain name globs as URL globs if the contains a `/`.

**Comment by MarquiseRosier** [comment]
@trieloff I think we should whitelist certain queries for users; so I'm down for another whitelist and a separate test. 

Then just do a 
mm.some(url.host, ext_data_embed_whitelist) || mm.some(url, hlx_data_embed_whitelist) 

I think we shouldn't mix hlx embeds with external ones

**Comment by trieloff** [comment]
I don't think we need to whitelist specific queries and I wouldn't want to have a new configuration setting, just something like this:

```json
    "DATA_EMBED_WHITELIST": {
      "type": "string",
      "description": "Comma-separated list of allowed hostnames for data embeds. Supports `*.example.com` as a subdomain wildcard. Use `*` to allow all embeds (potentially insecure and conflicting with `EMBED_WHITELIST`)",
      "default": "docs.google.com, *.sharepoint.com, */_query/*, https://adobeioruntime.net/api/v1/web/*/helix-services/run-query@v1/*"
    },
```

Then split the glob pattern at the first slash, evaluate the left part against the hostname (as we do now) and the right part (including the initial slash) against the pathname.

**Comment by MarquiseRosier** [comment]
I think i'll lump all these whitelist based changes together: 

https://github.com/adobe/helix-pipeline/issues/732

**Comment by MarquiseRosier** [comment]
This was completed with https://github.com/adobe/helix-data-embed/pull/44
