### ISSUE TITLE
add slideshare embeds

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-pipeline#735]
**Description**
support embeds from www.slideshare.net

because they aren't whitelisted but supported by Iframely  :) 

https://blog.adobe.com/en/drafts/migrated/2020/05/27/where-is-personalization-missing-the-mark.html

**Comment by rofe** [comment]
@MarquiseRosier weird, SlideShare embed was already working here before: https://theblog-adobe.hlx.page/en/drafts/embed-test.html
