### ISSUE TITLE
Add fonts step

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pipeline#753]
Add a pipeline step which rewrites absolute Adobe Fonts (typekit) URLs to relative `/hlx_fonts/*` URLs. This will speed up the page because the font file can be delivered from the same host.

Change
```html
<link rel="stylesheet" href="https://use.typekit.net/pps7abe.css"/>
```
To
```html
<link rel="stylesheet" href="/hlx_fonts/pps7abe.css"/>
```

**Comment by trieloff** [comment]
Do we want the same in helix-static?

**Comment by rofe** [comment]
Not sure I see the use case, could you elaborate?

**Comment by trieloff** [comment]
The user defined HTML you see in Helix Pages isn't going through the pipeline (unless you use markup.yaml) so it won't benefit from this feature.

**Comment by rofe** [comment]
You're right, of course... but how could helix-static help?

**Comment by trieloff** [comment]
We already rewrite JS and CSS there. Adding HTML wouldn't be hard.
