### ISSUE TITLE
timestamp is displayed unexpectedly

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pipeline#755]
in the middle of...

https://theblog--adobe.hlx.page/en/drafts/migrated/2020/05/21/adobe-celebrates-global-accessibility-awareness-day.html#gs.7sd5nq

...the layout seems broken. search for 00.

i think this may be an icon `:07:`. to be perfectly honest i am not sure that this really is an importer issue, but ideally this should be escaped some how during the import.

**Comment by kptdobe** [comment]
Moving to helix-pipeline since this is a rendering issue. Interesting issue...

The icon logic which is too invasive.

Created an md file that contains:

```
We start at 9:07:00
```

Rendering is:

```
<p>We start at 9<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-07"><use href="/icons/07.svg"></use></svg>00</p>
```

**Comment by kptdobe** [comment]
Source: https://github.com/adobe/helix-pipeline/issues/500

**Comment by kptdobe** [comment]
>  ideally this should be escaped some how during the import.

I do not think this should be escaped!! We must be able to enter a date in our content without get an icon, no ?

**Comment by rofe** [comment]
Thanks @kptdobe I'll look into it.

**Comment by ramboz** [comment]
@rofe, @kptdobe: would it be enough to change the regexp https://github.com/adobe/helix-pipeline/pull/506/files#diff-506d7ce34c50b4067f41a3cb258344d8R14 to just require to be surrounded by whitespace and/or punctuation?

- `foo:bar:baz` => untouched
- `foo:bar: baz` => untouched
- `foo :bar:baz` => untouched
- `foo :bar: baz` => `foo <svg…/> baz`
- `foo :bar:,` => `foo <svg…/>,`
- `foo :bar:!` => `foo <svg…/>!`
- `:bar:!` => `<svg…/>!`
- `::bar:` => `:<svg…/>`
- etc.

So something like`/(^|[^\w]):([a-z0-9_-]+):([^\w]|$)/gi` instead

**Comment by rofe** [comment]
@ramboz I tried your regexp (and other variants of whitespace or non-digit surrounding characters) but it will always fail one of the tests in `testIconize.js`. For now it felt safer to settle for the requirement to start icon IDs with a letter (see #757).

**Comment by ramboz** [comment]
@rofe Did you also adjust the matching logic?

As I introduced additional groups in the regexp the "noise" around the icons is also included in the output, so it would fail if you try to parse, say `" :foo:,"`. You would need to only take the internal group that has `":foo:"`.

```js
const regexp = /(?:^|\W)(:([a-z0-9_-]+):)(?:\W|$)/gi;
...
const icons = node.value.matchAll(regexp);
if (icons) {
  ...
  [...icons].forEach(([_, match, iconName]) => {
    ...
  }
}
```
- input: `"bar :foo:, baz qux"`
- regex groups: `[" :foo:,", ":foo:", "foo"]`

So you can also avoid the substring computation later to get the icon name.

The `testIconize.js` pass for me with this
