### ISSUE TITLE
Weird combo of line breaks and inline tags causes issues

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pipeline#756]
Some articles seem to produce md files with a h1 title followed by an empty h3, and they appear to be the cause of 500 errors during rendering:
```
TypeError: head.value.replace is not a function at all 
```

Examples:
- en/drafts/migrated/2016/11/30/partner-overview-mirum.md
- en/drafts/migrated/2017/10/18/updates-for-video-and-audio-tools-are-here.md

While this could be handled more gracefully in the pipeline, we should probably try to avoid setting an emtpy h3.

**Comment by kptdobe** [comment]
This line is the issue: https://github.com/adobe/helix-pipeline/blob/master/src/utils/mdast-to-vdom.js#L84

The HAST cannot contain a `DocumentFragment` as value because it is expected to be a "string". Need to understand why we have those lines.

**Comment by kptdobe** [comment]
With #349, we deviate from the spec thus we cannot rely on libraries like which rely on the spec (expects value must be a string). This is the case for `mdast-util-to-hast`: https://github.com/adobe/helix-pipeline/blob/master/src/utils/mdast-to-vdom.js#L16

Underline does not exist in Markdown, thus I think the case where we mix `<u>` in md tags is valid.
Or at least, it should be robust and not crash the full pipeline.

@tripodsan: you made those changes, feedback welcomed ;)

**Comment by tripodsan** [comment]
see similar issue #499 and #501
