### ISSUE TITLE
content proxy requests should go through fastly.

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#795]
**Is your feature request related to a problem? Please describe.**
in order to support better caching of content, it should be fetched through fastly, instead via the content-proxy.

**Describe the solution you'd like**
change the `fetch-content` step to fetch the content from `${cdn-url}/${resourcePath}.md`

/cc @trieloff @davidnuescheler

**Comment by trieloff** [comment]
This depends on our ability to flush the Fastly cache for content-proxy resources.

**Comment by tripodsan** [comment]
@davidnuescheler @trieloff should we request via the sha or the branch? i.e.:

- https://master--theblog--adobe.hlx.page/en/publish/2021/02/01/adobe-celebrates-black-history-month.md

or

- https://3a9584738053710f0e2745438599ec0b8a8d2120--theblog--adobe.hlx.page/en/publish/2021/02/01/adobe-celebrates-black-history-month.md

**Comment by trieloff** [comment]
If we have the sha, use it, otherwise we have to resolve it again in the content proxy.

**Comment by tripodsan** [comment]
> If we have the sha, use it, otherwise we have to resolve it again in the content proxy.

true!
