### ISSUE TITLE
Icons currently not working

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pipeline#817]
From @davidnuescheler in #509:
> currently we seem to render something like:
> 
> ```
> <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-twitter">
> <use href="/icons/twitter.svg"></use>
> </svg>
> ```
> 
> which simply doesn't work without the id and `#` in the `href`.
> 
> so i would propose that we switch to the `icons.svg#<id>` notation unless someone has a `use` version that works without touching the actual svg file.

> after looking a little bit more into this and having usecases where it is pretty useful to use the same icons also for the favicons, i think that a project should be able to support both. icons in the `/icons` folder and icons that are in the `icons.svg` symbol sheet.
> 
> the easiest way to distinguish those would be to support `:logo:` and `:#logo:` notation respectively...
> 
> `:logo:` would product something like a `<img class="icon icon-logo" src="/icons/logo.svg">` while `:#logo:` would produce `<svg class="icon icon-logo"><use xlink:href="/icons.svg#logo"></use></svg>`

**Comment by davidnuescheler** [comment]
this is protoyped on the client side here:
https://staging--pages--adobe.hlx.page/illustrator/en/twp/step-2
see icons in `header` and `footer` vs. `main`
the issue that i encountered is the that the `#<icon>` notation doesn't seem to work with our current parsing, so in the meantime i used a `i-<icon>` as a prefix to suggest that icon coming from `icons.svg`.
to me `#` feels most intuitive, but i am open to anything else if we need to go too deep into md parsing to make it work.

**Comment by rofe** [comment]
## Icon output until v10.5.1
`:logo:` produced the following (broken) markup:
```html
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-logo">
<use href="/icons/logo.svg"></use>
</svg>
```
## Icon output starting 11.0.0
`:logo:` will assume there is a file named `/icons/logo.svg` and produce the folloiwng markup:
```html
<img class="icon icon-logo" src="/icons/logo.svg">
```
`:#logo:` will assume `logo` is the ID of an icon in an icon collection file `/icons.svg` and produce the following markup:
```html
<svg class="icon icon-logo"><use xlink:href="/icons.svg#logo"></use></svg>
```
