### ISSUE TITLE
detection of "likely links" in the pipeline

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#819]
> should the detection of "likely links" be something done in the pipeline?

I think that would be a nice feature.

_Originally posted by @rofe in https://github.com/adobe/theblog/issues/314#issuecomment-668424448_

**Comment by tripodsan** [comment]
@rofe can you elaborate or close the issue,

**Comment by rofe** [comment]
I don't think we need that anymore. Word and Gdoc will always prepend a protocol anyway.

cc @trieloff
