### ISSUE TITLE
4xx responses from content-proxy should be reported back to dispatch.

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#831]
**Description**
4xx responses are intended for situations in which the error seems to have been caused by the client. Instead of returning a 502, we should report back the original error.

**Expected behavior**
We are currently only treating 404 specially, but we should return all 4xx responses as-is:
https://github.com/adobe/helix-pipeline/blob/c5f76bf8ffd7f929ba9aac780a6a7a92a5e2b6c3/src/utils/Downloader.js#L154

**Comment by trieloff** [comment]
A 400 should become a 500, as this is an error within the pipeline. The current 502 is also wrong, as the gateway has done no wrong

**Comment by tripodsan** [comment]
> A 400 should become a 500, as this is an error within the pipeline. The current 502 is also wrong, as the gateway has done no wrong

In this case, the 400 was caused by an illegal path fed into the pipeline. so the content proxy throws a 400, which is perfectly ok. I disagree that the 400 should become a 500.

similarly, a 429 should remain a 429 and potentially turned into a 500 in the CDN in order to hide it.

**Comment by trieloff** [comment]
> In this case, the 400 was caused by an illegal path fed into the pipeline.

The way I see it, pipeline is responsible for making proper HTTP requests. If it doesn't, the error is the pipeline's. If pipeline knows a certain path to be invalid, it should reject (400) it itself.
