### ISSUE TITLE
Extend "section maker" to support headings

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#86]
Background: currently the [split-section.js]() only create sections if the markdown contains thematic breaks, which by default is never the case. Splitting per headings if there is no thematic break would allow to have sections in all cases and to create some section based design even for "standard" markdown.

This is a follow up of discussion in https://github.com/adobe/Adobe-Developer-Site/issues/11.

**Comment by kptdobe** [comment]
From @trieloff:

> we can easily write something similar for creating one document per header, so that in a document that has headers like this: h1 h2 h2 h3 h2 h3 h3 h2, you would get following sections:
> * h1 h2 h2 h3 h2 h3 h3 h2
>* h2
>* h2 h3
>* h3
>* h2 h3 h3 h2
>* h3
>* h3
>* h2
> 
> The algorithm looks like this: visit all headings and for each heading create a new section. For each section, remove all nodes that come before the heading. Also remove the next heading that has a level equal or higher to the one selected and all following nodes.

**Comment by kptdobe** [comment]
I am not sure if this is really useful and I do not really like the duplicates of content: you cannot process the sections as is, you always need to do another treatment to be able to do something with this output.

In your sample h1 h2 h2 h3 h2 h3 h3 h2, the bigger issue is the first h1 that we almost always remove and consider as the page title. If you eliminate the first h1, I would expect to get something like:

* h2
* h2 h3
* h2 h3 h3
* h2

I do not think we need to go deeper than one level (h1 if more than one or h2 (leading h1 becoming the main title)) and this would align well with the thematic break "sectionification" (also only one level).
Looking at existing doc like https://github.com/Adobe-Marketing-Cloud/reactor-user-docs/edit/master/getting-started/web.md, this would be enough for now and would cover the needs for the index in Algolia (I do not think you want to index at an h3 level, too few context...).

For more complex treatments, we would need concrete real life use cases before generating something too complex.

I am current exploring what we could do.

**Comment by trieloff** [comment]
Irrespective of how you want to split by heading, I think that a heading splitter is fundamentally different from a section splitter and should be implemented separately, so I'd rather have this issue be called "implement heading splitter".

**Comment by kptdobe** [comment]
I am not sure about that. I think both tries to accomplish the same goal: group things together in order to give those groups a purpose (and then a specific rendering). thematic break is an explicit way of grouping, headers are the next thing we can use to guess a grouping.
I am still trying to make a use case, let see where I land. It is trivial anyway to merge both in sections or to create another container.

**Comment by ramboz** [comment]
I wonder, according to the HTML5 spec headings actually introduce implicit sectioning.
See:
- https://www.w3.org/TR/2011/WD-html5-author-20110809/headings-and-sections.html
- https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines

If I understood the spec correctly this also means that the following examples are semantically identical:

Flat hierarchy:
```html
<body>
  <h1>Apples</h1>
  <p>Apples are fruit.</p>
  <h2>Taste</h2>
  <p>They taste lovely.</p>
  <h3>Sweet</h3>
  <p>Red apples are sweeter than green ones.</p>
  <h2>Color</h2>
  <p>Apples come in various colors.</p>
</body>
```

Sectioned content:
```html
<body>
  <h1>Apples</h1>
  <p>Apples are fruit.</p>
  <section>
    <h2>Taste</h2>
    <p>They taste lovely.</p>
    <section>
      <h3>Sweet</h3>
      <p>Red apples are sweeter than green ones.</p>
    </section>
  </section>
  <section>
    <h2>Color</h2>
    <p>Apples come in various colors.</p>
  </section>
</body>
```

Non-linear sections and headers.
```html
<body>
  <h4>Apples</h4>
  <p>Apples are fruit.</p>
  <section>
     <h2>Taste</h2>
     <p>They taste lovely.</p>
     <h6>Sweet</h6>
     <p>Red apples are sweeter than green ones.</p>
     <h1>Color</h1>
     <p>Apples come in various colors.</p>
  </section>
</body>
```

While I definitely do not particularly like the last code example, I am of the opinion that we could automatically turn the 1st into the 2nd to offer more structure, and easier styling as well.

**Comment by kptdobe** [comment]
The "sectionification" is useful to compute the "type" to the section. Making it explicit is definitively helpful. 
+1 to follow the nice version of the spec.
sections are anyway stored in a separate property, the no-hierarchy version is still available.

**Comment by trieloff** [comment]
See https://github.com/adobe/helix-pipeline/issues/279#issuecomment-489573206 – I'd vote to close this issue.

**Comment by ramboz** [comment]
@kptdobe Ok to close?
