### ISSUE TITLE
regression escaping tags from gdoc

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pipeline#883]
this may or may not be a pipeline issue.

in the pages project we used markers in the document that look like tags

```
<steps>
```

this used to be rendered to

```
<p>&lt;steps&gt;</p>
```

and is now rendered to

```
<p>\<steps></steps></p>
```

i think this points to a number of issues at hand. first we need to upgrade our test harness and secondly this looks like tags are not escaped anymore coming from a google doc?

**Comment by tripodsan** [comment]
this is the same problem again with the new remark parser/stringify. we don't have the new one in place in pipeline, so the roundtrip doesn't work.
