### ISSUE TITLE
bold links where text is a url does not render properly

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#895]
Example: https://theblog--adobe.hlx.page/en/drafts/alex/links.html

Does not work:

```markdown
[**www.richardianson.com**](https://richardianson.com/)
```

Works:
```markdown
[**Instagram**](https://richardianson.com/)
```

This sample is coming from a docx but sample applies with a markdown file, the issue is then in the pipeline

**Comment by tripodsan** [comment]
what's the HTML output?

**Comment by kptdobe** [comment]
```html
<p>[**<a href="http://www.richardianson.com**%5D(https://richardianson.com/)" rel="noopener" target="_blank">www.richardianson.com**](https://richardianson.com/)</a></p>
```

**Comment by kptdobe** [comment]
Btw, something similar happens is the text starts with https:

```markdown
<**https://www.richardianson.com**>
```

gives

```html
<p>&lt;**<a href="https://www.richardianson.com**%3E">https://www.richardianson.com**&gt;</a></p>
```

**Comment by kptdobe** [comment]
The Korean version of theblog site has plenty of those...

**Comment by tripodsan** [comment]
I'll have a look

**Comment by tripodsan** [comment]
> Btw, something similar happens is the text starts with https:
> 
> ```gfm
> <**https://www.richardianson.com**>
> ```

I think this is wrongly generated.... event github doesn't understand this:

<**https://www.richardianson.com**>

it should better be:

```gfm
**<https://www.richardianson.com>**
```

**<https://www.richardianson.com>**

**Comment by tripodsan** [comment]
see https://github.com/syntax-tree/mdast-util-gfm-autolink-literal/issues/1

**Comment by tripodsan** [comment]
see https://github.com/adobe/helix-word2md/issues/477

**Comment by kptdobe** [comment]
Not sure if this deserves another issue but I found another broken case:

```md
**[프리미어 러시 CC(Premiere Rush CC)](http://theblog.adobe.com/create-and-share-online-videos-anywhere-with-all-new-premiere-rush-cc/)**
```

**Comment by tripodsan** [comment]
works for me in the test (`testHTMLFromMarkdown.js`):

```js
  it('korean link', async () => {
    await assertMd(
      '**[프리미어 러시 CC(Premiere Rush CC)](http://theblog.adobe.com/create-and-share-online-videos-anywhere-with-all-new-premiere-rush-cc/)**\n',
      '<p><strong><a href="http://theblog.adobe.com/create-and-share-online-videos-anywhere-with-all-new-premiere-rush-cc/">프리미어 러시 CC(Premiere Rush CC)</a></strong></p>',
    );
  });
```

**Comment by kptdobe** [comment]
Re-opening since this is only fixed when coming from a Word document. In my case, source is an md file (import). See https://theblog--adobe.hlx.page/ko/publish/2016/03/02/how-to-create-3d-models-in-photoshop.html

**Comment by tripodsan** [comment]
sorry. it's not possible to fix this w/o syntax-tree/mdast-util-gfm-autolink-literal#1. so the best would probably be if the 
importer either escapes the hostnames inside the bold links, or moves the bold out of the links. so either:

```
**[https://stock.adobe.com/stock-photo/modern-mobile-phone/91187020](https://stock.adobe.com/stock-photo/modern-mobile-phone/91187020)**
```

or

```
[**https\://stock\.adobe\.com/stock-photo/modern-mobile-phone/91187020**](https://stock.adobe.com/stock-photo/modern-mobile-phone/91187020)
```

**Comment by kptdobe** [comment]
Ok. I am on it, thx.

**Comment by tripodsan** [comment]
btw: I don't see any corrupt links in the document??

**Comment by kptdobe** [comment]
Yes, because I fix them on the import side, sorry. 
I should take the habit of isolating the broken stuff in a separate document.

Recreated the broken links I have found in: https://theblog--adobe.hlx.page/en/drafts/alex/brokenlinks.html
