### ISSUE TITLE
Strikethrough: only with double tildes

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#897]
Koreans seems to use the notation "number~number" (20~30) - could find it in 14 file out of 376 (~5%).
If you put 2 in the same paragraph, strikethrough is applied in between the 2 tildes (see https://hlxsite-kptdobe.hlx.page/emphasis.html).

One solution would be to only apply the strikethrough if 2 tildes are used.

**Comment by tripodsan** [comment]
you need to escape them... 

eg: "number\~number" (20\~30)

**Comment by kptdobe** [comment]
Ok. But still not so natural for the end-user.
Does word2md do it automatically ?
