### ISSUE TITLE
Reduce log level for 404

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#908]
While observing our logs in Coralogix, the large majority of the `warn` I can see are coming from this project line: https://github.com/adobe/helix-pipeline/blob/main/src/utils/Downloader.js#L165

which in 99% of the cases I am observing at the moment are for "valid" 404 requests which are part of our "concurrent check for resources" which for sure tries combos to files which do not exist. Those do not deserve a `warn` but a `debug` (eventually an `info`).

The overflow of those warnings hides the "real" warnings we should be worried about.

@trieloff @tripodsan WDYT ?

This one works together with https://github.com/adobe/helix-content-proxy/issues/239
In this normal flow of requests https://helix.coralogix.com/#/query/logs?id=2AtbscscPSC, 103 warnings, 1 is a "real" warning.

**Comment by tripodsan** [comment]
`info` would be enough for a 404.
