### ISSUE TITLE
Schema validation - disable for now

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#92]
The schema validation is a really annoying feature : for every single new non-handled case, the rendering the broken. 

New one: 
```
[hlx] warn: tapping failed: Error: Invalid Context at step 2
data.content.mdast.children[9].meta should be string undefined, data.content.mdast.children[11].meta should be string undefined, data.content.mdast.children[13].meta should be string undefined, data.content.mdast.children[15].meta should be string undefined
```
Multiple issues:

1. The logs are `warn` while the validation blocks the rendering. They should be `error`.
2. Appart from adding a break point at the right place in the pipeline (for the record, this line https://github.com/adobe/hypermedia-pipeline/blob/master/src/utils/validate.js#L46), impossible to know what is wrong
3. To unblock the rendering, you need to patch the current hlx version

My proposal here is to keep the messages as `warnings` and to disable the "blocking" aspect of the validation. 

cc @trieloff

**Comment by kptdobe** [comment]
Workaround for 2.: inspect `logs/debug/context_dump_*` files. 

But this does not reduce the annoyance of the non rendering of the request.

**Comment by trieloff** [comment]
I know that it is annoying, but I think it is the fastest way of getting the schemas in sync with reality.

**Comment by trieloff** [comment]
We are pretty close now, so I'd close this.

**Comment by ramboz** [comment]
@trieloff The `every` step for the validation will still trigger for each `error` step as well, so the error message is repeated several times with no added benefit.

I'm reopening and proposing a quick fix for that
