### ISSUE TITLE
HTTP Timeout too low

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#935]
We are getting too many 504s from pipeline duo to HTTP timeouts. Let's bump by 2x

https://github.com/adobe/helix-pipeline/blob/2ff56e4a5e31ddb5b1896a537c746be9fd273559/src/schemas/secrets.schema.json#L71

**Comment by tripodsan** [comment]
same for the external timeout, we  should bump it to `20000`

**Comment by stefan-guggisberg** [comment]
> same for the external timeout, we should bump it to `20000`

it's already `20000`: https://github.com/adobe/helix-pipeline/blob/2ff56e4a5e31ddb5b1896a537c746be9fd273559/src/schemas/secrets.schema.json#L76
