### ISSUE TITLE
content fetch via fastly should use branch (not ref)

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#985]
using the `ref` seems to be the right choice, eg:

`https://57d920944f401e677e2467a680c47c0f61544983--theblog-adobe.hlx.page/index.md`

but there are several problems:

- it's very obscure for a human to know the correct ref to purge, in case something goes wrong
- since the ref is the commit sha from the content repository, any change in a helix-pages project to a github file, will invalidate all content (eg. style, script, etc)
- most of the content sources from onedrive or google drive anyways, hence the ref is irrelevant

there is a benefit of using the ref:

- changes to the fstab invalidate all cached content
- it's easy to invalidate all content by simply commiting to github
- projects that only use github as content source have purging for free

Suggest to use the `branch` name only.

**Comment by tripodsan** [comment]
@trieloff WDYT?

**Comment by stefan-guggisberg** [comment]
Not sure it's relevant here, but the reasons we're resolving a `ref` (branch or tag name) to a commit `sha` in helix:

* raw.githubusercontent.com urls (served by fastly) containing a `ref` are not guaranteed to return the current state of the resource (due to caching), i.e. modifying a resource on `main` and requesting it using the ref `main` might return a stale copy. commit `sha`s solve this problem.
* resources identified by the `sha` are immutable and can be cached indefinitely

**Comment by trieloff** [comment]
As Stefan pointed out, the branch has some caching on GitHub, which we saw as a deal breaker at the time and hence created the resolve-git-ref infrastructure. If we think this is acceptable, then we should use branches everywhere.

> it's very obscure for a human to know the correct ref to purge, in case something goes wrong

but that can be handled in `helix-purge` which can calculate the surrogate-keys to purge

> since the ref is the commit sha from the content repository, any change in a helix-pages project to a github file, will invalidate all content (eg. style, script, etc)

is this relevant for the pipeline?

> most of the content sources from onedrive or google drive anyways, hence the ref is irrelevant

and that means I'd rather leave things as they are.

**Comment by tripodsan** [comment]
> As Stefan pointed out, the branch has some caching on GitHub, which we saw as a deal breaker at the time and hence created the resolve-git-ref infrastructure. If we think this is acceptable, then we should use branches everywhere.

this is different. most of the content origins from onedrive/googledrive...

> > it's very obscure for a human to know the correct ref to purge, in case something goes wrong
> 
> but that can be handled in `helix-purge` which can calculate the surrogate-keys to purge

but then we need a surrogate key for it. the current content proxy only stores the document source, which is not known to helix-purge.

> > since the ref is the commit sha from the content repository, any change in a helix-pages project to a github file, will invalidate all content (eg. style, script, etc)
> 
> is this relevant for the pipeline?

no, but for the cache efficiency. projects with a high client side dev, will bust their content cache with every modification.

> > most of the content sources from onedrive or google drive anyways, hence the ref is irrelevant
> 
> and that means I'd rather leave things as they are.

The problem is, that helix-purge then needs to do a git-resolve-ref in order to be able to purge the `.md` correctly (@rofe 

@davidnuescheler WDYT?

**Comment by trieloff** [comment]
> projects with a high client side dev, will bust their content cache with every modification.

They will bust the cache for `md` files served from GitHub, which I'd say is a good thing.

> The problem is, that `helix-purge` then needs to do a `git-resolve-ref` in order to be able to purge the `.md` correctly (@rofe)

As I suggested in https://github.com/adobe/helix-purge/issues/128#issuecomment-787751257 we could normalize the URL for surrogate key calculation, so that `/foo.html` and `/foo.md` will have the same surrogate key and `helix-purge` will purge both at the same time.

**Comment by tripodsan** [comment]
> > projects with a high client side dev, will bust their content cache with every modification.
> 
> They will bust the cache for `md` files served from GitHub, which I'd say is a good thing.

no, the problem is, that the `sha` is used for all _content_, even for the one not in github.
so a css/js modification in a helix pages project, will invalidate modify the sha that is used for the `.html` actions, and hence by the pipeline to fetch a `.md` (even if the source is onedrive/gdrive)

> > The problem is, that `helix-purge` then needs to do a `git-resolve-ref` in order to be able to purge the `.md` correctly (@rofe)
> 
> As I suggested in [adobe/helix-purge#128 (comment)](https://github.com/adobe/helix-purge/issues/128#issuecomment-787751257) we could normalize the URL for surrogate key calculation, so that `/foo.html` and `/foo.md` will have the same surrogate key and `helix-purge` will purge both at the same time.

but what is the surrogate key?

**Comment by trieloff** [comment]
We have one more option:

https://github.com/adobe/helix-publish/blob/9cd121ca5a003f65139f5103d43c758147efff2e/layouts/fastly/helix.vcl#L1323-L1329

We can use `https://${branch}--repo--owner.hlx.page/${path}.md?ref=${sha}` and then use surrogate-key tricks to purge all `https://${branch}--repo--owner.hlx.page/${path}` variants.

This would also provide a way to address the long hostname problem you have seen.

**Comment by tripodsan** [comment]
we already add the _github_ url as surrogate key source for the html:
https://github.com/adobe/helix-pipeline/blob/main/src/html/fetch-content.js#L79

we should probably do the same for the `.md` from the content-proxy

**Comment by trieloff** [comment]
> we should probably do the same for the `.md` from the content-proxy

I think the right way would be to add the `.md` URL to the surrogate key + all surrogate-key headers that the `.md` URL produces. Then we can remove the GH URL from the direct calculation of the surrogate key.

**Comment by tripodsan** [comment]
what I mean is, assume a request to `https://theblog--adobe.hlx.page/foo.html`, when we should use:

```
https://github.com/adobe/theblog/master/foo.md
``

as a source for the surrogate key for all html action responses and also the content-proxy response

**Comment by trieloff** [comment]
I would construct the surrogate key only out of the sources that are actually requested + whatever surrogate keys these sources send, so that each layer is only responsible of knowing its own sources and propagating the upstream surrogate keys.

**Comment by trieloff** [comment]
After talking with @davidnuescheler and @rofe, let's revisit my earlier comment:

> As Stefan pointed out, the branch has some caching on GitHub, which we saw as a deal breaker at the time and hence created the `resolve-git-ref` infrastructure. If we think this is acceptable, then we should use branches everywhere.

- We now see the minimal caching in github as acceptable
- hence **we should use *branch* names to fetch in helix-pipeline**
- and drop the use of `helix-resolve-git-ref` in `helix-dispatch` and `helix-content-proxy`
- and proceed with adobe/helix-purge#128 as planned (purge the branch URL)
